#!/usr/bin/env python
"""
Claude Code Session Reporter
Scans all Claude Code sessions for recent activity and produces concise
reports of what was accomplished, where things left off, etc.

Summaries are generated by Claude Code itself via the /session-report slash
command, which orchestrates: collect -> summarize -> cache -> render.
This script handles data collection, caching, and rendering only.

Works on Windows, macOS, and Linux — reads from ~/.claude/ which is the same
structure on all platforms.

Usage:
    python claude-session-report.py [days]              # default: 3 days, HTML
    python claude-session-report.py 7                   # last 7 days
    python claude-session-report.py 1 --text            # terminal text output
    python claude-session-report.py 3 --no-ai           # ignore cached summaries
    python claude-session-report.py 3 --limit 20        # only process 20 most recent sessions
    python claude-session-report.py 7 text              # bare words work too (no -- needed)

    # Used by the /session-report slash command:
    python claude-session-report.py 3 --collect         # output sessions needing summaries
    python claude-session-report.py --update-cache F    # merge summaries from JSON file F
    python claude-session-report.py 3 --review-statuses # output folder-grouped summaries for status review
    python claude-session-report.py --update-statuses F # apply status corrections from JSON file F
"""

import json
import os
import sys
import re
import argparse
import tempfile
import webbrowser
from datetime import datetime, timedelta, timezone
from pathlib import Path
from collections import defaultdict
from html import escape as html_escape

# Fix Windows console encoding
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

CLAUDE_DIR = Path.home() / ".claude"
PROJECTS_DIR = CLAUDE_DIR / "projects"
SESSIONS_DIR = CLAUDE_DIR / "sessions"
HISTORY_FILE = CLAUDE_DIR / "history.jsonl"
CACHE_FILE = CLAUDE_DIR / "session-report-cache.json"
REPORT_DIR = CLAUDE_DIR / "reports"
HOME_STR = str(Path.home())

MIN_MESSAGES_FOR_AI = 4

STATUS_LABELS = {
    "in_progress": "In Progress",
    "blocked": "Blocked",
    "handed_off": "Handed Off",
    "complete": "Complete",
    "unknown": "Unsummarized",
}
STATUS_ORDER = {"blocked": 0, "in_progress": 1, "handed_off": 2, "unknown": 3, "complete": 4}
STATUS_TOOLTIPS = {
    "in_progress": "Actively being worked on",
    "blocked": "Hit a blocker and paused",
    "handed_off": "Ended expecting continuation in a new session",
    "complete": "Work in this session is finished",
    "unknown": "Not yet summarized by AI",
}


# ─── Cache ────────────────────────────────────────────────────────────────────


def load_summary_cache() -> dict:
    if not CACHE_FILE.exists():
        return {}
    try:
        with open(CACHE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def save_summary_cache(cache: dict) -> bool:
    try:
        fd, tmp_path = tempfile.mkstemp(dir=CACHE_FILE.parent, suffix=".tmp")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)
        Path(tmp_path).replace(CACHE_FILE)
        return True
    except OSError as e:
        print(f"  WARNING: Failed to write cache: {e}")
        return False


def get_cached_data(cache, session_id, msg_count, latest_ts):
    """Return dict with summary/status/title from cache, or None on miss."""
    entry = cache.get(session_id)
    if not entry:
        return None
    summary = entry.get("summary", "")
    if not summary or summary.startswith("(Haiku summary failed") or summary.startswith("(error"):
        return None
    if entry.get("msg_count") == msg_count and entry.get("latest_ts") == latest_ts:
        return {
            "summary": summary,
            "status": entry.get("status", "unknown"),
            "title": entry.get("title", ""),
        }
    return None


def read_corrections_from_previous_report():
    """Read status corrections embedded in the most recent report HTML.

    Returns dict of {session_id: new_status} or empty dict.
    """
    if not REPORT_DIR.exists():
        return {}
    reports = sorted(REPORT_DIR.glob("session-report-*.html"), key=lambda f: f.stat().st_mtime, reverse=True)
    if not reports:
        return {}

    try:
        content = reports[0].read_text(encoding="utf-8")
    except OSError:
        return {}

    # Extract JSON from <script type="application/json" id="status-corrections">
    match = re.search(
        r'<script\s+type="application/json"\s+id="status-corrections">\s*(\{.*?\})\s*</script>',
        content, re.DOTALL
    )
    if not match:
        return {}

    try:
        corrections = json.loads(match.group(1))
        if isinstance(corrections, dict):
            # Validate entries
            valid = {}
            for sid, status in corrections.items():
                if isinstance(status, str) and status in STATUS_LABELS:
                    valid[sid] = status
            if valid:
                print(f"  Found {len(valid)} status correction(s) from previous report")
            return valid
    except json.JSONDecodeError:
        pass

    return {}


def apply_corrections_to_cache(corrections):
    """Apply user corrections to the summary cache."""
    if not corrections:
        return
    cache = load_summary_cache()
    updated = 0
    for sid, new_status in corrections.items():
        if sid in cache and cache[sid].get("status") != new_status:
            cache[sid]["status"] = new_status
            updated += 1
    if updated > 0:
        save_summary_cache(cache)
        print(f"  Applied {updated} status correction(s) to cache")


# ─── Helpers ──────────────────────────────────────────────────────────────────


def clean_transcript_text(text):
    """Strip XML command tags and other noise from message text."""
    if not text:
        return ""
    text = re.sub(r'<command-name>.*?</command-name>', '', text, flags=re.DOTALL)
    text = re.sub(r'<command-message>.*?</command-message>', '', text, flags=re.DOTALL)
    text = re.sub(r'<command-args>.*?</command-args>', '', text, flags=re.DOTALL)
    text = re.sub(r'<local-command-caveat>.*?</local-command-caveat>', '', text, flags=re.DOTALL)
    text = re.sub(r'<system-reminder>.*?</system-reminder>', '', text, flags=re.DOTALL)
    text = re.sub(r'<task-notification>.*?</task-notification>', '', text, flags=re.DOTALL)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def truncate(text, max_len=120):
    text = text.replace("\n", " ").strip()
    return text if len(text) <= max_len else text[: max_len - 3] + "..."


def format_timestamp(ts):
    if not ts:
        return "unknown"
    local = ts.astimezone()
    now = datetime.now(timezone.utc).astimezone()
    if local.date() == now.date():
        return f"Today {local.strftime('%I:%M %p')}"
    elif local.date() == (now - timedelta(days=1)).date():
        return f"Yesterday {local.strftime('%I:%M %p')}"
    else:
        return local.strftime("%b %d %I:%M %p")


def format_timestamp_short(ts):
    if not ts:
        return ""
    local = ts.astimezone()
    now = datetime.now(timezone.utc).astimezone()
    if local.date() == now.date():
        return f"Today {local.strftime('%I:%M %p')}"
    elif local.date() == (now - timedelta(days=1)).date():
        return "Yesterday"
    else:
        return local.strftime("%b %d")


def format_duration(start, end):
    """Format duration between two datetimes as human-readable string."""
    if not start or not end:
        return ""
    delta = end - start
    total_minutes = int(delta.total_seconds() / 60)
    if total_minutes < 60:
        return f"{total_minutes}m"
    hours = total_minutes // 60
    minutes = total_minutes % 60
    if minutes == 0:
        return f"{hours}h"
    return f"{hours}h {minutes}m"


def short_path(folder):
    if folder.startswith(HOME_STR):
        return "~" + folder[len(HOME_STR):]
    return folder


def clean_user_text(text):
    text = text.strip()
    if not text or len(text) < 5:
        return None
    for p in ("[tool result", "[Request interrupted", "<task-notification",
              "<command-", "<local-command", "# Screenshot"):
        if text.startswith(p):
            return None
    if text.startswith("This session is being continued"):
        return "(continued from previous session)"
    return text


def extract_title_from_summary(summary):
    """Extract a short title from the first sentence after ## Summary."""
    if not summary:
        return None
    lines = summary.split("\n")
    found = False
    for line in lines:
        stripped = line.strip()
        if stripped.lower().startswith("## summary"):
            found = True
            continue
        if found and stripped and not stripped.startswith("#"):
            sentence = stripped.split(". ")[0]
            if len(sentence) > 80:
                sentence = sentence[:77] + "..."
            return sentence
    return None


# ─── Session parsing ─────────────────────────────────────────────────────────


def decode_project_path(encoded: str) -> str:
    parts = encoded.split("--")
    if sys.platform == "win32":
        if parts and len(parts[0]) == 1 and parts[0].isalpha():
            drive = parts[0] + ":"
            return drive + "\\" + "\\".join(parts[1:])
        return "\\".join(parts)
    else:
        if encoded.startswith("--"):
            return "/" + "/".join(parts[1:])
        if parts and len(parts[0]) == 1 and parts[0].isalpha():
            return parts[0] + ":/" + "/".join(parts[1:])
        return "/".join(parts)


def extract_text_from_content(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts = []
        for block in content:
            if isinstance(block, dict):
                if block.get("type") == "text":
                    texts.append(block.get("text", ""))
                elif block.get("type") == "tool_use":
                    texts.append(f"[tool: {block.get('name', '')}]")
            elif isinstance(block, str):
                texts.append(block)
        return " ".join(texts)
    return str(content)


def parse_session_file(filepath):
    messages = []
    session_id = None
    cwd = None
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                entry_type = entry.get("type")
                if entry_type not in ("user", "assistant"):
                    continue
                if not session_id:
                    session_id = entry.get("sessionId")
                if not cwd:
                    cwd = entry.get("cwd")
                timestamp_str = entry.get("timestamp")
                timestamp = None
                if timestamp_str:
                    try:
                        if isinstance(timestamp_str, str):
                            timestamp = datetime.fromisoformat(timestamp_str.replace("Z", "+00:00"))
                        elif isinstance(timestamp_str, (int, float)):
                            timestamp = datetime.fromtimestamp(timestamp_str / 1000, tz=timezone.utc)
                    except (ValueError, OSError):
                        pass
                msg = entry.get("message", {})
                role = msg.get("role", entry_type)
                content = msg.get("content", "")
                text = extract_text_from_content(content)
                if text and text.strip():
                    messages.append({"role": role, "text": text.strip(), "timestamp": timestamp})
    except (OSError, PermissionError):
        return None
    if not messages:
        return None
    return {"session_id": session_id or filepath.stem, "cwd": cwd, "messages": messages}


def get_session_cwd_from_sessions_dir():
    mapping = {}
    if not SESSIONS_DIR.exists():
        return mapping
    for f in SESSIONS_DIR.glob("*.json"):
        try:
            with open(f, "r", encoding="utf-8", errors="replace") as fh:
                data = json.loads(fh.read())
                sid = data.get("sessionId")
                cwd = data.get("cwd")
                if sid and cwd:
                    mapping[sid] = cwd
        except (json.JSONDecodeError, OSError):
            pass
    return mapping


def get_history_sessions():
    sessions = defaultdict(lambda: {"project": None})
    if not HISTORY_FILE.exists():
        return sessions
    try:
        with open(HISTORY_FILE, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                try:
                    entry = json.loads(line.strip())
                    sid = entry.get("sessionId")
                    if sid and entry.get("project"):
                        sessions[sid]["project"] = entry["project"]
                except json.JSONDecodeError:
                    continue
    except OSError:
        pass
    return sessions


# ─── Collect sessions ────────────────────────────────────────────────────────


def collect_sessions(days):
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    history_sessions = get_history_sessions()
    session_cwd_map = get_session_cwd_from_sessions_dir()
    all_sessions = []

    if not PROJECTS_DIR.exists():
        return all_sessions

    print("Scanning sessions...", end="", flush=True)

    for project_dir in sorted(PROJECTS_DIR.iterdir()):
        if not project_dir.is_dir():
            continue
        project_path = decode_project_path(project_dir.name)

        for session_file in project_dir.glob("*.jsonl"):
            try:
                mtime = datetime.fromtimestamp(session_file.stat().st_mtime, tz=timezone.utc)
                if mtime < cutoff:
                    continue
            except OSError:
                continue

            data = parse_session_file(session_file)
            if not data or not data["messages"]:
                continue

            timestamps = [m["timestamp"] for m in data["messages"] if m["timestamp"]]
            if not timestamps:
                continue
            latest = max(timestamps)
            earliest = min(timestamps)
            if latest < cutoff:
                continue

            cwd = data["cwd"]
            sid = data["session_id"]
            if not cwd and sid in session_cwd_map:
                cwd = session_cwd_map[sid]
            if not cwd and sid in history_sessions:
                cwd = history_sessions[sid]["project"]
            if not cwd:
                cwd = project_path

            user_msgs = [m for m in data["messages"] if m["role"] == "user"]
            assistant_msgs = [m for m in data["messages"] if m["role"] == "assistant"]

            topics = []
            for m in user_msgs:
                clean = clean_user_text(m["text"])
                if clean:
                    topics.append(truncate(clean, 100))

            first_ask = topics[0] if topics else (
                truncate(clean_transcript_text(user_msgs[0]["text"]), 200) if user_msgs else "N/A"
            )

            last_user = last_assistant = None
            for m in reversed(data["messages"]):
                if m["role"] == "user" and not last_user:
                    last_user = m["text"]
                if m["role"] == "assistant" and not last_assistant:
                    last_assistant = m["text"]
                if last_user and last_assistant:
                    break

            all_sessions.append({
                "session_id": sid,
                "cwd": cwd,
                "project_path": project_path,
                "earliest": earliest,
                "latest": latest,
                "user_msg_count": len(user_msgs),
                "assistant_msg_count": len(assistant_msgs),
                "total_messages": len(data["messages"]),
                "first_ask": first_ask,
                "topics": topics,
                "last_user": last_user,
                "last_assistant": last_assistant,
                "raw_messages": data["messages"],
            })
            print(".", end="", flush=True)

    print(f" done! ({len(all_sessions)} sessions found)\n")
    all_sessions.sort(key=lambda s: s["latest"], reverse=True)
    return all_sessions


# ─── Transcript sampling ─────────────────────────────────────────────────────


def prepare_transcript(session_data):
    messages = session_data.get("raw_messages", [])
    if len(messages) <= 20:
        sampled = messages
    else:
        first = messages[:6]
        last = messages[-6:]
        mid_start = len(messages) // 3
        mid_end = 2 * len(messages) // 3
        middle = messages[mid_start : mid_start + 4] + messages[mid_end : mid_end + 4]
        sampled = (
            first
            + [{"role": "system", "text": f"... ({len(messages) - 20} messages omitted) ..."}]
            + middle
            + last
        )

    transcript_parts = []
    for m in sampled:
        text = clean_transcript_text(m["text"][:500])
        if not text or len(text) < 5:
            continue
        if text.startswith("[tool result") or text.startswith("[tool:"):
            continue
        transcript_parts.append(f"{m['role'].upper()}: {text}")

    transcript = "\n".join(transcript_parts)[:12000]
    return transcript


# ─── Summaries ────────────────────────────────────────────────────────────────


def load_cached_summaries(all_sessions, no_ai=False):
    """Load cached summaries. Returns {session_id: {summary, status, title}}."""
    if no_ai:
        return {}
    cache = load_summary_cache()
    summaries = {}
    cached_count = 0
    for s in all_sessions:
        sid = s["session_id"]
        latest_ts = s["latest"].isoformat() if s["latest"] else ""
        cached = get_cached_data(cache, sid, s["total_messages"], latest_ts)
        if cached:
            summaries[sid] = cached
            cached_count += 1
    if cached_count:
        print(f"  {cached_count} session(s) loaded from summary cache")
    return summaries


def collect_for_summarization(all_sessions, max_collect, refresh):
    cache = {} if refresh else load_summary_cache()
    results = []
    skipped = 0
    already_cached = 0

    for s in all_sessions:
        sid = s["session_id"]
        if s["total_messages"] < MIN_MESSAGES_FOR_AI:
            skipped += 1
            continue
        latest_ts = s["latest"].isoformat() if s["latest"] else ""
        if not refresh:
            cached = get_cached_data(cache, sid, s["total_messages"], latest_ts)
            if cached:
                already_cached += 1
                continue

        transcript = prepare_transcript(s)
        if len(transcript.strip()) < 50:
            skipped += 1
            continue

        results.append({
            "session_id": sid,
            "cwd": s.get("cwd", "unknown"),
            "msg_count": s["total_messages"],
            "latest_ts": latest_ts,
            "folder": s.get("cwd", s.get("project_path", "")),
            "transcript": transcript,
        })

        if max_collect > 0 and len(results) >= max_collect:
            break

    return {
        "sessions": results,
        "total_found": len(all_sessions),
        "already_cached": already_cached,
        "too_short": skipped,
        "needs_summary": len(results),
    }


def _validate_report_path(filepath):
    """Validate that filepath is within ~/.claude/reports/."""
    try:
        resolved = Path(filepath).resolve()
        allowed = REPORT_DIR.resolve()
        if not str(resolved).startswith(str(allowed) + os.sep) and resolved != allowed:
            print(f"Error: file path must be within {REPORT_DIR}")
            return False
    except (OSError, ValueError) as e:
        print(f"Error validating file path: {e}")
        return False
    return True


def update_cache_from_file(filepath):
    if not _validate_report_path(filepath):
        return False
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            new_entries = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"Error reading summaries file: {e}")
        return False

    cache = load_summary_cache()
    merged = 0
    for sid, entry in new_entries.items():
        if not isinstance(entry, dict) or "summary" not in entry:
            print(f"  Skipping {sid}: missing 'summary' field")
            continue
        cache[sid] = {
            "summary": entry["summary"],
            "status": entry.get("status", "unknown"),
            "title": entry.get("title", ""),
            "msg_count": entry.get("msg_count"),
            "latest_ts": entry.get("latest_ts", ""),
            "folder": entry.get("folder", ""),
        }
        merged += 1

    if not save_summary_cache(cache):
        return False
    print(f"  Merged {merged} summary(ies) into cache")
    return True


# ─── Two-pass status review ──────────────────────────────────────────────────


def prepare_review_data(all_sessions, summaries):
    """Group sessions by folder with their cached summaries for cross-session status review."""
    by_folder = defaultdict(list)
    for s in all_sessions:
        sid = s["session_id"]
        s_data = summaries.get(sid, {})
        if not isinstance(s_data, dict) or not s_data.get("summary"):
            continue
        by_folder[s["cwd"] or s["project_path"]].append({
            "session_id": sid,
            "title": s_data.get("title", ""),
            "status": s_data.get("status", "unknown"),
            "summary": s_data["summary"],
            "latest_ts": s["latest"].isoformat() if s["latest"] else "",
        })

    folders = []
    for folder, sessions in sorted(by_folder.items()):
        if len(sessions) > 1:
            sessions.sort(key=lambda x: x["latest_ts"])
            folders.append({
                "folder": folder,
                "session_count": len(sessions),
                "sessions": sessions,
            })

    return {
        "folders": folders,
        "needs_review": len(folders),
    }


def update_statuses_from_file(filepath):
    """Update only the status field for existing cache entries."""
    if not _validate_report_path(filepath):
        return False
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            corrections = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"Error reading status corrections: {e}")
        return False

    cache = load_summary_cache()
    updated = 0
    for sid, entry in corrections.items():
        if sid not in cache:
            print(f"  Skipping {sid}: not in cache")
            continue
        new_status = entry.get("status") if isinstance(entry, dict) else entry
        if new_status and new_status in STATUS_LABELS:
            old_status = cache[sid].get("status", "unknown")
            if old_status != new_status:
                cache[sid]["status"] = new_status
                updated += 1

    if updated > 0:
        if not save_summary_cache(cache):
            return False
    print(f"  Updated {updated} session status(es)")
    return True


# ─── Markdown conversion ─────────────────────────────────────────────────────


def md_to_html(text):
    lines = text.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()
        if in_list and not stripped.startswith("- ") and not stripped.startswith("* "):
            html_lines.append("</ul>")
            in_list = False
        if stripped.startswith("## "):
            html_lines.append(f"<h3>{html_escape(stripped[3:])}</h3>")
        elif stripped.startswith("# "):
            html_lines.append(f"<h2>{html_escape(stripped[2:])}</h2>")
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            content = html_escape(stripped[2:])
            content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', content)
            content = re.sub(r'`(.+?)`', r'<code>\1</code>', content)
            html_lines.append(f"<li>{content}</li>")
        elif stripped == "":
            continue
        else:
            content = html_escape(stripped)
            content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', content)
            content = re.sub(r'`(.+?)`', r'<code>\1</code>', content)
            html_lines.append(f"<p>{content}</p>")

    if in_list:
        html_lines.append("</ul>")
    return "\n".join(html_lines)


# Section accent colors (muted tinted neutrals — distinct from status colors)
SECTION_STYLES = {
    "what was done": ("oklch(0.55 0.03 55)", "done"),
    "what was accomplished": ("oklch(0.55 0.03 55)", "done"),
    "summary": ("oklch(0.55 0.03 55)", "done"),
    "key decisions": ("oklch(0.50 0.025 200)", "decisions"),
    "decisions made": ("oklch(0.50 0.025 200)", "decisions"),
    "decisions": ("oklch(0.50 0.025 200)", "decisions"),
    "issues encountered": ("oklch(0.52 0.035 25)", "issues"),
    "issues": ("oklch(0.52 0.035 25)", "issues"),
    "blockers": ("oklch(0.52 0.035 25)", "issues"),
    "next steps": ("oklch(0.50 0.03 130)", "next"),
    "what's next": ("oklch(0.50 0.03 130)", "next"),
}

# Sections that should be rendered as the "Next Steps" card instead of a color-coded block
NEXT_STEPS_SECTIONS = {"next steps", "what's next"}


def parse_summary_sections(summary_text):
    """Parse summary markdown into structured sections for color-coded rendering.

    Returns (sections_list, next_steps_entry_or_None).
    sections_list: list of {label, css_class, color, html_content} dicts.
    next_steps: a single {label, css_class, color, html} dict or None.
    Falls back to a single 'Summary' section if no recognized headings found.
    """
    if not summary_text or summary_text.startswith("("):
        return [], None

    lines = summary_text.split("\n")
    sections = []
    current_label = None
    current_lines = []

    for line in lines:
        stripped = line.strip()
        heading_match = re.match(r'^#{1,3}\s+(.+)$', stripped)
        if heading_match:
            # Save previous section
            if current_label is not None and current_lines:
                sections.append((current_label, "\n".join(current_lines)))
            current_label = heading_match.group(1).strip()
            current_lines = []
        else:
            current_lines.append(line)

    # Save final section
    if current_label is not None and current_lines:
        sections.append((current_label, "\n".join(current_lines)))

    # If no headings found, treat entire text as one section
    if not sections:
        return [{
            "label": "Summary",
            "css_class": "done",
            "color": "oklch(0.55 0.03 55)",
            "html": md_to_html(summary_text),
        }], None

    result = []
    next_steps = None
    for label, content in sections:
        label_lower = label.lower().strip()
        color, css_class = SECTION_STYLES.get(label_lower, ("oklch(0.55 0.03 55)", "done"))
        html = md_to_html(content)
        if not html.strip():
            continue
        entry = {"label": label, "css_class": css_class, "color": color, "html": html}
        # Separate "Next Steps" for special card rendering
        if label_lower in NEXT_STEPS_SECTIONS:
            next_steps = entry
        else:
            result.append(entry)

    if not result:
        result = [{"label": "Summary", "css_class": "done",
                    "color": "oklch(0.55 0.03 55)", "html": md_to_html(summary_text)}]

    return result, next_steps  # next_steps may be None


def aggregate_projects(all_sessions, summaries, days):
    """Group sessions by project with computed metadata for the sidebar."""
    by_project = defaultdict(list)
    now = datetime.now(timezone.utc)
    inactive_threshold = now - timedelta(hours=24)

    for s in all_sessions:
        sid = s["session_id"]
        s_data = summaries.get(sid, {})
        if isinstance(s_data, dict):
            s["_summary"] = s_data.get("summary", "")
            s["_status"] = s_data.get("status", "unknown")
            s["_title"] = s_data.get("title") or extract_title_from_summary(s_data.get("summary", ""))
        else:
            s["_summary"] = ""
            s["_status"] = "unknown"
            s["_title"] = None
        if not s["_title"]:
            fallback_title = s.get("first_ask") or ""
            fallback_title = re.sub(r'^#+\s+', '', fallback_title.lstrip())
            s["_title"] = truncate(fallback_title, 80) if fallback_title else "(untitled)"
        by_project[s["cwd"] or s["project_path"]].append(s)

    projects = []
    for folder, sessions in by_project.items():
        sessions.sort(key=lambda x: x["latest"], reverse=True)
        latest_session = sessions[0]
        status_counts = defaultdict(int)
        for s in sessions:
            status_counts[s["_status"]] += 1

        # Active/inactive: inactive if all sessions complete and latest > 24h ago
        latest_time = max(s["latest"] for s in sessions)
        all_complete = all(s["_status"] in ("complete", "unknown", "handed_off") for s in sessions)
        is_inactive = all_complete

        # Project-level status: simple active vs inactive (session-level statuses remain unchanged)
        project_status = "inactive" if is_inactive else "active"

        # Short name: last component of the path
        sp = short_path(folder)
        if sp == "~":
            short_name = "Home"
            initials = "HM"
        else:
            short_name = sp.rstrip("/\\").split("/")[-1].split("\\")[-1]
            # Initials: first two chars of first two words, or first two chars
            parts = re.split(r'[-_]', short_name)
            if len(parts) >= 2:
                initials = (parts[0][0] + parts[1][0]).upper()
            else:
                initials = short_name[:2].upper()

        projects.append({
            "folder": folder,
            "short_path": short_path(folder),
            "name": short_name,
            "initials": initials,
            "sessions": sessions,
            "session_count": len(sessions),
            "latest": latest_time,
            "status": project_status,
            "status_counts": dict(status_counts),
            "is_inactive": is_inactive,
            "last_title": latest_session["_title"],
        })

    # Sort: active first (by recency, Home deprioritized), then inactive (by recency)
    active = sorted([p for p in projects if not p["is_inactive"]], key=lambda p: (p["name"] != "Home", p["latest"]), reverse=True)
    inactive = sorted([p for p in projects if p["is_inactive"]], key=lambda p: p["latest"], reverse=True)

    return active, inactive


# ─── HTML output ──────────────────────────────────────────────────────────────


def generate_html(all_sessions, summaries, days):
    # ── Aggregate projects ──────────────────────────────────
    active_projects, inactive_projects = aggregate_projects(all_sessions, summaries, days)
    # Unified list sorted by recency (Home deprioritized)
    all_projects = sorted(
        active_projects + inactive_projects,
        key=lambda p: (p["name"] != "Home", p["latest"]),
        reverse=True
    )
    total_projects = len(all_projects)
    now_str = datetime.now().strftime("%b %d, %Y %I:%M %p")

    # Status variable mapping
    STATUS_VAR = {
        "in_progress": "progress",
        "blocked": "blocked",
        "handed_off": "handed",
        "complete": "complete",
        "unknown": "text-3",
        "active": "progress",
        "inactive": "text-3",
    }

    def _time_ago(ts):
        """Format timestamp as relative time ago string."""
        if not ts:
            return ""
        now = datetime.now(timezone.utc)
        delta = now - ts
        minutes = int(delta.total_seconds() / 60)
        if minutes < 60:
            return f"{minutes}m ago"
        hours = minutes // 60
        if hours < 24:
            return f"{hours}h ago"
        d = hours // 24
        return f"{d}d ago"

    # ── Pre-render all project data for JSON embedding ──────
    projects_json = []
    for proj in all_projects:
        sessions_data = []
        for s in proj["sessions"]:
            summary_text = s.get("_summary", "")
            sections, next_steps = parse_summary_sections(summary_text)

            # Pre-render summary HTML
            sections_html = ""
            for sec in sections:
                # Extract first bullet as collapsed preview
                preview = ""
                import re as _re
                li_match = _re.search(r'<li[^>]*>(.*?)</li>', sec["html"], _re.DOTALL)
                if li_match:
                    preview_text = _re.sub(r'<[^>]+>', '', li_match.group(1)).strip()
                    # Unescape HTML entities before re-escaping for the preview
                    from html import unescape as _unescape
                    preview_text = _unescape(preview_text)
                    preview = html_escape(truncate(preview_text, 120))

                sections_html += (
                    '<div class="summary-block collapsed" onclick="toggleSummaryBlock(this)">'
                    f'<div class="summary-bar" style="background:var(--section-{html_escape(sec["css_class"])})"></div>'
                    '<div class="summary-block-inner">'
                    f'<div class="summary-block-header">'
                    f'<div class="summary-block-label" style="color:var(--section-{html_escape(sec["css_class"])})">{html_escape(sec["label"])}</div>'
                    f'<span class="summary-block-chevron">&#9656;</span>'
                    f'</div>'
                    f'<div class="summary-block-preview">{preview}</div>'
                    f'<div class="summary-block-full"><div class="summary-block-content">{sec["html"]}</div></div>'
                    '</div></div>'
                )
            next_steps_html = next_steps["html"] if next_steps else ""

            # Fallback summary for unsummarized sessions
            if not sections_html and summary_text and not summary_text.startswith("("):
                sections_html = (
                    '<div class="summary-block">'
                    '<div class="summary-bar" style="background:var(--section-done)"></div>'
                    '<div>'
                    '<div class="summary-block-label" style="color:var(--section-done)">Summary</div>'
                    f'<div class="summary-block-content">{md_to_html(summary_text)}</div>'
                    '</div></div>'
                )
            elif not sections_html:
                # Raw fallback for unsummarized sessions
                first_ask_text = s["first_ask"].strip() if s.get("first_ask") else ""
                if first_ask_text:
                    fallback_parts = [f'<p><strong>Opening ask:</strong> {html_escape(truncate(first_ask_text, 300))}</p>']
                else:
                    fallback_parts = [f'<p><strong>Opening ask:</strong> <em>(slash command)</em></p>']
                if s.get("last_assistant"):
                    clean = clean_transcript_text(s["last_assistant"])
                    if clean and len(clean) > 10:
                        fallback_parts.append(f'<p><strong>Last response:</strong> {html_escape(truncate(clean, 300))}</p>')
                sections_html = (
                    '<div class="summary-block">'
                    '<div class="summary-bar" style="background:var(--section-done)"></div>'
                    '<div>'
                    '<div class="summary-block-label" style="color:var(--section-done)">Session</div>'
                    f'<div class="summary-block-content">{"".join(fallback_parts)}</div>'
                    '</div></div>'
                )

            sessions_data.append({
                "session_id": s["session_id"],
                "title": s["_title"] or "",
                "status": s["_status"],
                "summary_html": sections_html,
                "next_steps_html": next_steps_html,
                "time_str": format_timestamp_short(s["latest"]),
                "time_long": format_timestamp(s["latest"]),
                "msgs": s["total_messages"],
                "duration": format_duration(s["earliest"], s["latest"]),
            })

        projects_json.append({
            "folder": proj["folder"],
            "name": proj["name"],
            "short_path": proj["short_path"],
            "initials": proj["initials"],
            "status": proj["status"],
            "session_count": proj["session_count"],
            "latest_str": _time_ago(proj["latest"]),
            "last_title": proj["last_title"] or "",
            "is_inactive": proj["is_inactive"],
            "status_counts": proj.get("status_counts", {}),
            "sessions": sessions_data,
        })

    # Escape for safe embedding in <script>
    projects_json_str = json.dumps(projects_json, ensure_ascii=False)
    projects_json_str = projects_json_str.replace("</script>", "<\\/script>")

    # ── Count statuses ─────────────────────────
    n_inactive_proj = sum(1 for p in all_projects if p["status"] == "inactive")

    # ── Build unified sidebar project list (all projects by recency) ──
    sidebar_items = []
    for i, proj in enumerate(all_projects):
        status = proj["status"]
        sv = STATUS_VAR.get(status, "text-3")
        name_esc = html_escape(proj["name"])
        title_esc = html_escape(proj["last_title"] or "")
        time_ago = _time_ago(proj["latest"])
        n_sess = proj["session_count"]
        selected = " selected" if i == 0 else ""
        is_inactive = status == "inactive"

        if is_inactive:
            badge_html = f'<span class="project-status project-status-inactive" onclick="showProjectStatusDropdown(this,{i},event)">Inactive <span class="dd">&#9660;</span></span>'
        else:
            badge_style = f'style="background:var(--{sv}-bg);color:var(--{sv})"'
            badge_html = f'<span class="project-status" {badge_style} onclick="showProjectStatusDropdown(this,{i},event)">Active <span class="dd">&#9660;</span></span>'

        sidebar_items.append(
            f'<div class="project-item{selected}{" inactive" if is_inactive else ""}" data-project-index="{i}" '
            f'data-status="{status}" onclick="selectProject({i})">'
            f'<div class="project-avatar"{" style=opacity:0.5" if is_inactive else ""}>{html_escape(proj["initials"])}'
            f'<div class="avatar-dot" style="background:var(--{sv})"></div></div>'
            f'<div class="project-name-row">'
            f'<span class="project-name">{name_esc}</span>'
            f'{badge_html}'
            f'</div>'
            f'<div class="project-last-session">{title_esc}</div>'
            f'<div class="project-time">{html_escape(time_ago)}</div>'
            f'</div>'
        )

    # ── Build first project detail panel (server-side default) ──
    first_detail = ""
    if all_projects:
        fp = all_projects[0]
        fp_status = fp["status"]
        fp_sv = STATUS_VAR.get(fp_status, "text-3")
        fp_label = "Active" if fp_status == "active" else "Inactive"
        fp_badge_style = f'style="background:var(--{fp_sv}-bg);color:var(--{fp_sv})"'

        # First session data for the summary
        fp_sessions = projects_json[0]["sessions"] if projects_json else []
        fp_first = fp_sessions[0] if fp_sessions else None

        first_detail_parts = []
        # Header (project-level badge — no dropdown, computed status)
        first_detail_parts.append(
            '<div class="detail-header"><div class="detail-top-row"><div>'
            f'<div class="detail-project-name">{html_escape(fp["name"])}</div>'
            f'<div class="detail-project-path">{html_escape(fp["short_path"])}</div>'
            '</div>'
            f'<span class="detail-badge" style="background:var(--{fp_sv}-bg);color:var(--{fp_sv});cursor:pointer" '
            f'onclick="showProjectStatusDropdown(this,0,event)">'
            f'{fp_label} <span class="dd">&#9660;</span></span>'
            '</div></div>'
        )

        if fp_first:
            # Summary sections
            first_detail_parts.append(
                f'<div class="summary-sections">{fp_first["summary_html"]}</div>'
            )
            # Session meta
            first_detail_parts.append(
                '<div class="session-meta-row">'
                f'<span>{html_escape(fp_first["time_long"])}</span>'
                '<span class="meta-dot"></span>'
                f'<span>{fp_first["msgs"]} messages</span>'
                '<span class="meta-dot"></span>'
                f'<span>{html_escape(fp_first["duration"])}</span>'
                '</div>'
            )
            # Next steps
            if fp_first["next_steps_html"]:
                first_detail_parts.append(
                    '<div class="next-steps">'
                    '<div class="next-steps-label">Next Steps</div>'
                    f'{fp_first["next_steps_html"]}'
                    '</div>'
                )

        # Recent sessions timeline
        n_all_sess = len(fp_sessions)
        n_progress_sess = sum(1 for s in fp_sessions if s["status"] == "in_progress")
        n_complete_sess = sum(1 for s in fp_sessions if s["status"] == "complete")

        timeline_items = []
        for si, sess in enumerate(fp_sessions):
            s_sv = STATUS_VAR.get(sess["status"], "text-3")
            s_label = STATUS_LABELS.get(sess["status"], sess["status"])
            if sess["status"] == "unknown":
                s_badge_style = 'style="color:var(--text-3);background:transparent;border:1px dashed var(--border)"'
            else:
                s_badge_style = f'style="background:var(--{s_sv}-bg);color:var(--{s_sv})"'

            timeline_items.append(
                f'<div class="timeline-item" data-status="{sess["status"]}" onclick="toggleTimeline(this)">'
                '<div class="timeline-top">'
                f'<span class="timeline-title">{html_escape(sess["title"])}</span>'
                f'<span class="timeline-badge" {s_badge_style} '
                f'onclick="showStatusDropdown(this,\'{html_escape(sess["session_id"])}\',event)">'
                f'{s_label} <span class="dd">&#9660;</span></span>'
                '</div>'
                '<div class="timeline-meta">'
                f'<span>{html_escape(sess["time_str"])}</span>'
                '<span class="meta-dot"></span>'
                f'<span>{sess["msgs"]} msgs</span>'
                '<span class="meta-dot"></span>'
                f'<span>{html_escape(sess["duration"])}</span>'
                '</div>'
                '<div class="timeline-expansion"><div class="timeline-expansion-inner">'
                f'<div class="timeline-expansion-text">{sess["summary_html"]}</div>'
                '</div></div>'
                '</div>'
            )

        first_detail_parts.append(
            '<div class="recent-sessions">'
            '<div class="recent-header">'
            '<div class="section-label" style="margin-bottom:0">Recent Sessions</div>'
            '<div class="detail-filters">'
            f'<button class="detail-filter active" onclick="filterSessions(\'all\',this)">All {n_all_sess}</button>'
            + (f'<button class="detail-filter" onclick="filterSessions(\'in_progress\',this)">In Progress {n_progress_sess}</button>' if n_progress_sess else "")
            + (f'<button class="detail-filter" onclick="filterSessions(\'complete\',this)">Complete {n_complete_sess}</button>' if n_complete_sess else "")
            + '</div></div>'
            f'<div class="session-timeline">{"".join(timeline_items)}</div>'
            '</div>'
        )
        first_detail = "".join(first_detail_parts)

    # ── Assemble HTML ───────────────────────────────────────
    html = f"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Session Report &mdash; Last {days} day(s)</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&display=swap" rel="stylesheet">
<style>
/* ── Reset ─────────────────────────────────────────────── */
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

/* ── Theme: Dark (default) ─────────────────────────────── */
:root {{
  --bg:           oklch(0.12 0.008 55);
  --surface:      oklch(0.155 0.01 55);
  --surface-2:    oklch(0.185 0.012 55);
  --surface-hover: oklch(0.21 0.014 55);
  --border:       oklch(0.24 0.012 55);
  --border-2:     oklch(0.30 0.012 55);
  --text:         oklch(0.92 0.01 55);
  --text-2:       oklch(0.72 0.01 55);
  --text-3:       oklch(0.50 0.01 55);
  --text-3-bg:    oklch(0.22 0.01 55);
  --text-4:       oklch(0.38 0.01 55);
  --progress:     oklch(0.72 0.14 250);
  --progress-bg:  oklch(0.22 0.04 250);
  --blocked:      oklch(0.75 0.12 70);
  --blocked-bg:   oklch(0.22 0.04 70);
  --handed:       oklch(0.72 0.14 300);
  --handed-bg:    oklch(0.22 0.04 300);
  --complete:     oklch(0.68 0.10 160);
  --complete-bg:  oklch(0.20 0.03 160);
  --section-done:      oklch(0.55 0.03 55);
  --section-decisions: oklch(0.50 0.025 200);
  --section-issues:    oklch(0.52 0.035 25);
  --shadow-sm: 0 1px 2px oklch(0 0 0 / 0.15);
  --shadow-md: 0 4px 12px oklch(0 0 0 / 0.2);
  --radius: 8px;
  --step-0: clamp(0.8rem, 0.77rem + 0.15vw, 0.875rem);
  --step-1: clamp(0.875rem, 0.84rem + 0.18vw, 1rem);
  --step-2: clamp(1rem, 0.95rem + 0.25vw, 1.15rem);
  --step-3: clamp(1.25rem, 1.15rem + 0.5vw, 1.5rem);
  color-scheme: dark;
}}

/* ── Theme: Light ──────────────────────────────────────── */
[data-theme="light"] {{
  --bg: oklch(0.97 0.005 55);
  --surface: oklch(0.94 0.007 55);
  --surface-2: oklch(0.91 0.008 55);
  --surface-hover: oklch(0.88 0.01 55);
  --border: oklch(0.85 0.008 55);
  --border-2: oklch(0.78 0.01 55);
  --text: oklch(0.15 0.02 55);
  --text-2: oklch(0.35 0.015 55);
  --text-3: oklch(0.55 0.01 55);
  --text-3-bg: oklch(0.92 0.008 55);
  --text-4: oklch(0.68 0.008 55);
  --progress: oklch(0.50 0.18 250);
  --progress-bg: oklch(0.94 0.04 250);
  --blocked: oklch(0.55 0.16 70);
  --blocked-bg: oklch(0.94 0.04 70);
  --handed: oklch(0.50 0.17 300);
  --handed-bg: oklch(0.94 0.04 300);
  --complete: oklch(0.48 0.12 160);
  --complete-bg: oklch(0.94 0.04 160);
  --section-done: oklch(0.45 0.03 55);
  --section-decisions: oklch(0.42 0.025 200);
  --section-issues: oklch(0.44 0.035 25);
  color-scheme: light;
}}

/* ── Accessibility ─────────────────────────────────────── */
@media (prefers-reduced-motion: reduce) {{
  *, *::before, *::after {{ animation: none !important; transition-duration: 0.01ms !important; }}
}}

/* ── Base ──────────────────────────────────────────────── */
body {{
  background: var(--bg);
  color: var(--text);
  font-family: 'Outfit', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
  line-height: 1.55;
  -webkit-font-smoothing: antialiased;
  height: 100dvh;
  overflow: hidden;
}}

/* ── Layout ────────────────────────────────────────────── */
.layout {{ display: flex; height: 100dvh; }}

/* ── Sidebar ───────────────────────────────────────────── */
.sidebar {{
  width: clamp(260px, 18vw, 340px);
  height: 100%;
  border-right: 1px solid var(--border);
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  background: var(--surface);
  transition: width 0.3s cubic-bezier(0.16, 1, 0.3, 1);
  overflow: hidden;
}}
.sidebar.collapsed {{ width: 56px; }}

/* Sidebar Header */
.sidebar-header {{
  padding: 22px 20px 16px;
  border-bottom: 1px solid var(--border);
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  min-height: 68px;
}}
.sidebar-brand {{ overflow: hidden; white-space: nowrap; transition: opacity 0.2s; }}
.sidebar.collapsed .sidebar-brand {{ opacity: 0; width: 0; }}
.sidebar-title {{ font-size: var(--step-2); font-weight: 700; letter-spacing: -0.025em; }}
.sidebar-sub {{ color: var(--text-3); font-size: var(--step-0); margin-top: 2px; }}
.sidebar-toggle {{
  background: var(--surface-2); border: 1px solid var(--border); border-radius: 6px;
  width: 30px; height: 30px; cursor: pointer; display: grid; place-items: center;
  font-size: 15px; color: var(--text-3); flex-shrink: 0; transition: all 0.15s;
  font-family: system-ui;
}}
.sidebar-toggle:hover {{ background: var(--surface-hover); color: var(--text-2); }}
.sidebar.collapsed .sidebar-header {{ justify-content: center; padding: 16px 0; min-height: auto; }}
.sidebar.collapsed .sidebar-toggle {{ margin: 0; }}
.sidebar.collapsed .sidebar-toggle .chevron {{ transform: rotate(180deg); }}
.chevron {{ display: inline-block; transition: transform 0.3s cubic-bezier(0.16, 1, 0.3, 1); }}

/* Sidebar Search */
.sidebar-search {{ padding: 10px 20px; border-bottom: 1px solid var(--border); }}
.sidebar.collapsed .sidebar-search {{ display: none; }}
.search-input {{
  width: 100%; background: var(--bg); border: 1px solid var(--border); color: var(--text);
  padding: 8px 12px; border-radius: var(--radius); font-size: var(--step-0);
  font-family: inherit; outline: none; transition: border-color 0.15s;
}}
.search-input::placeholder {{ color: var(--text-4); }}
.search-input:focus {{ border-color: var(--text-3); }}

/* Inactive toggle */
.inactive-toggle {{
  display: flex; align-items: center; gap: 6px; cursor: pointer;
  font-size: 0.72rem; color: var(--text-4); user-select: none;
  font-family: inherit;
}}
.inactive-toggle:hover {{ color: var(--text-3); }}
.inactive-cb {{ accent-color: var(--text-3); cursor: pointer; margin: 0; }}
.sidebar.collapsed .inactive-toggle {{ font-size: 0; gap: 0; }}

/* Project List */
.project-list {{ flex: 1; overflow-y: auto; padding: 6px 0; }}
.project-item {{
  padding: 13px 20px; cursor: pointer; transition: background 0.1s;
  border-left: 2px solid transparent;
}}
.project-item:hover {{ background: var(--surface-hover); }}
.project-item.selected {{
  background: var(--surface-2);
  border-left-color: var(--progress);
}}
.sidebar.collapsed .project-item {{
  padding: 6px 0; display: flex; justify-content: center; border-left: none;
}}
.project-name-row {{
  display: flex; justify-content: space-between; align-items: center; gap: 8px;
}}
.sidebar.collapsed .project-name-row {{ display: none; }}
.project-name {{ font-weight: 600; font-size: var(--step-0); color: var(--text-2); }}
.project-item.selected .project-name {{ color: var(--text); }}
.project-status {{
  font-size: 0.625rem; font-weight: 600; padding: 2px 8px; border-radius: 4px;
  text-transform: uppercase; letter-spacing: 0.04em; white-space: nowrap;
  display: flex; align-items: center; gap: 3px;
}}
.project-status-inactive {{
  background: var(--surface-2); color: var(--text-3);
  border: 1px solid var(--border);
}}
.project-status {{ cursor: pointer; }}
.project-status .dd {{ font-size: 6px; opacity: 0.5; }}
.project-last-session {{
  font-size: 0.78rem; color: var(--text-3); margin-top: 4px;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis; line-height: 1.4;
}}
.sidebar.collapsed .project-last-session {{ display: none; }}
.project-time {{ font-size: 0.72rem; color: var(--text-4); margin-top: 3px; }}
.sidebar.collapsed .project-time {{ display: none; }}

/* Collapsed Avatars */
.project-avatar {{
  display: none; width: 36px; height: 36px; border-radius: var(--radius);
  background: var(--surface-2); place-items: center; font-size: 0.72rem;
  font-weight: 600; color: var(--text-2); position: relative; cursor: pointer;
  transition: background 0.15s;
}}
.project-avatar:hover {{ background: var(--surface-hover); }}
.sidebar.collapsed .project-avatar {{ display: grid; }}
.project-item.selected .project-avatar {{ background: var(--progress-bg); color: var(--progress); }}
.avatar-dot {{
  position: absolute; bottom: 0; right: 0; width: 9px; height: 9px;
  border-radius: 50%; border: 2px solid var(--surface);
}}

/* Inactive Projects */
.project-item.inactive {{ opacity: 0.45; }}
.project-item.inactive:hover {{ opacity: 0.7; }}
.project-item.inactive.selected {{ opacity: 0.85; }}
.project-item.inactive.sr-hidden {{ display: none; }}

/* Sidebar Footer */
.sidebar-footer {{
  padding: 12px 20px; border-top: 1px solid var(--border);
  display: flex; align-items: center; justify-content: space-between; gap: 8px;
}}
.sidebar.collapsed .sidebar-footer {{ justify-content: center; padding: 12px 0; flex-direction: column; align-items: center; gap: 8px; }}
.sidebar.collapsed .inactive-toggle {{ font-size: 0; }}
.sidebar.collapsed .inactive-toggle .inactive-cb {{ font-size: initial; }}
.sidebar.collapsed .theme-text-btn {{ font-size: 0.6rem; }}
.sidebar.collapsed .footer-label {{ display: none; }}
.theme-btn {{
  background: var(--surface-2); border: 1px solid var(--border); border-radius: 6px;
  width: 30px; height: 30px; cursor: pointer; display: grid; place-items: center;
  font-size: 14px; color: var(--text-3); flex-shrink: 0; transition: all 0.15s;
}}
.theme-btn:hover {{ background: var(--surface-hover); color: var(--text-2); }}
.footer-label {{ font-size: 0.72rem; color: var(--text-4); }}

/* ── Detail Panel ──────────────────────────────────────── */
.detail {{ flex: 1; overflow-y: auto; background: var(--bg); position: relative; }}
/* Theme toggle */
.theme-toggle-btn {{
  background: none; border: none; cursor: pointer; padding: 0;
  line-height: 0; opacity: 0.7; transition: opacity 0.15s;
}}
.theme-toggle-btn:hover {{ opacity: 1; }}
.detail-inner {{ max-width: 780px; padding: 40px 48px; }}
.detail-header {{ margin-bottom: 32px; }}
.detail-top-row {{
  display: flex; justify-content: space-between; align-items: flex-start; gap: 16px;
}}
.detail-project-name {{
  font-family: 'Source Serif 4', 'Georgia', serif;
  font-size: var(--step-3); font-weight: 600; letter-spacing: -0.02em; line-height: 1.2;
}}
.detail-project-path {{
  color: var(--text-4); font-size: 0.78rem; margin-top: 6px;
  font-family: 'SFMono-Regular', 'Cascadia Code', Consolas, monospace;
}}
.detail-badge {{
  padding: 4px 14px; border-radius: 5px; font-size: 0.68rem; font-weight: 600;
  flex-shrink: 0; text-transform: uppercase; letter-spacing: 0.04em; cursor: pointer;
  display: flex; align-items: center; gap: 4px; transition: all 0.15s;
}}
.detail-badge:hover {{ filter: brightness(1.15); }}
.detail-badge .dd {{ font-size: 8px; opacity: 0.5; }}

/* Section Labels */
.section-label {{
  font-size: 0.7rem; font-weight: 600; text-transform: uppercase;
  letter-spacing: 0.08em; color: var(--text-3); margin-bottom: 12px;
}}

/* ── Summary Sections ──────────────────────────────────── */
.summary-sections {{
  margin-bottom: 32px; display: flex; flex-direction: column; gap: 12px;
}}
.summary-block {{ display: flex; gap: 14px; cursor: pointer; }}
.summary-block:hover {{ background: var(--surface-hover); margin: -8px -12px; padding: 8px 12px; border-radius: 6px; }}
.summary-bar {{ width: 3px; border-radius: 2px; flex-shrink: 0; }}
.summary-block-inner {{ flex: 1; min-width: 0; }}
.summary-block-header {{ display: flex; align-items: center; gap: 6px; }}
.summary-block-chevron {{ font-size: 0.7rem; color: var(--text-4); transition: transform 0.2s; }}
.summary-block:not(.collapsed) .summary-block-chevron {{ transform: rotate(90deg); }}
.summary-block-preview {{ font-size: 0.82rem; color: var(--text-3); margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
.summary-block:not(.collapsed) .summary-block-preview {{ display: none; }}
.summary-block-full {{ display: grid; grid-template-rows: 1fr; transition: grid-template-rows 0.25s ease; }}
.summary-block.collapsed .summary-block-full {{ grid-template-rows: 0fr; }}
.summary-block-full > .summary-block-content {{ overflow: hidden; }}
.summary-block-label {{ font-size: 0.78rem; font-weight: 600; margin-bottom: 6px; }}
.summary-block-content {{
  font-size: var(--step-0); color: var(--text-2); line-height: 1.65;
}}
.summary-block-content ul {{ padding-left: 18px; margin: 0; }}
.summary-block-content li {{ margin-bottom: 3px; }}
.summary-block-content p {{ margin: 4px 0; }}
.summary-block-content code {{
  background: var(--surface-2); padding: 1px 6px; border-radius: 4px;
  font-size: 0.82em; color: var(--blocked);
  font-family: 'SFMono-Regular', 'Cascadia Code', Consolas, monospace;
}}

/* Session Meta */
.session-meta-row {{
  color: var(--text-4); font-size: 0.78rem; margin-bottom: 32px;
  display: flex; align-items: center; gap: 8px;
}}
.meta-dot {{
  width: 3px; height: 3px; border-radius: 50%; background: var(--text-4); flex-shrink: 0;
}}

/* ── Next Steps Card ───────────────────────────────────── */
.next-steps {{
  background: var(--surface); border-radius: 10px; padding: 20px 24px;
  margin-bottom: 40px; border: 1px solid var(--border);
}}
.next-steps-label {{
  font-size: 0.7rem; font-weight: 600; text-transform: uppercase;
  letter-spacing: 0.08em; color: var(--text-3); margin-bottom: 10px;
}}
.next-steps ul {{
  color: var(--text-2); font-size: var(--step-0); line-height: 1.75; padding-left: 18px;
}}
.next-steps li {{ margin-bottom: 3px; }}
.next-steps li::marker {{ color: var(--text-4); }}

/* ── Recent Sessions Timeline ──────────────────────────── */
.recent-sessions {{ margin-bottom: 40px; }}
.recent-header {{
  display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px;
}}
.detail-filters {{ display: flex; gap: 4px; }}
.detail-filter {{
  background: transparent; border: 1px solid var(--border); color: var(--text-4);
  padding: 3px 9px; border-radius: 12px; font-size: 0.68rem; cursor: pointer;
  font-family: inherit; font-weight: 500; transition: all 0.15s;
}}
.detail-filter:hover {{ color: var(--text-3); border-color: var(--border-2); }}
.detail-filter.active {{ background: var(--surface-2); color: var(--text-2); border-color: var(--border-2); }}

.session-timeline {{
  position: relative; padding-left: 20px;
}}
.session-timeline::before {{
  content: ''; position: absolute; left: 3px; top: 8px; bottom: 8px;
  width: 1.5px; background: linear-gradient(to bottom, var(--border-2), var(--border), transparent);
}}
.timeline-item {{
  position: relative; padding: 10px 14px; margin-bottom: 2px;
  border-radius: var(--radius); cursor: pointer; transition: background 0.1s;
}}
.timeline-item:hover {{ background: var(--surface); }}
.timeline-item.filter-hidden {{ display: none; }}
.timeline-item::before {{
  content: ''; position: absolute; left: -17px; top: 16px;
  width: 7px; height: 7px; border-radius: 50%;
  background: var(--border-2); border: 2px solid var(--bg);
}}
.timeline-item:first-child::before {{
  background: var(--progress); box-shadow: 0 0 0 3px var(--progress-bg);
}}
.timeline-top {{
  display: flex; justify-content: space-between; align-items: center; gap: 12px;
}}
.timeline-title {{ color: var(--text-2); font-size: var(--step-0); font-weight: 500; }}
.timeline-item:first-child .timeline-title {{ color: var(--text); font-weight: 600; }}
.timeline-badge {{
  padding: 2px 8px; border-radius: 4px; font-size: 0.6rem; font-weight: 600;
  flex-shrink: 0; text-transform: uppercase; letter-spacing: 0.03em;
  display: flex; align-items: center; gap: 3px; cursor: pointer; transition: filter 0.15s;
}}
.timeline-badge:hover {{ filter: brightness(1.2); }}
.timeline-badge .dd {{ font-size: 6px; opacity: 0.5; }}
.timeline-meta {{
  color: var(--text-4); font-size: 0.75rem; margin-top: 3px;
  display: flex; align-items: center; gap: 6px;
}}

/* Expanded Timeline Session */
.timeline-expansion {{
  max-height: 0; overflow: hidden;
  transition: max-height 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}}
.timeline-item.expanded .timeline-expansion {{ max-height: 800px; }}
.timeline-expansion-inner {{
  background: var(--surface); border-radius: var(--radius);
  padding: 14px 18px; margin-top: 10px; border: 1px solid var(--border);
}}
.timeline-expansion-text {{
  color: var(--text-2); font-size: 0.82rem; line-height: 1.65; margin-bottom: 8px;
}}
.timeline-expansion-text .summary-block {{ margin-bottom: 12px; }}
.timeline-expansion-text .summary-block-label {{ font-size: 0.72rem; }}
.timeline-expansion-text .summary-block-content {{ font-size: 0.8rem; }}
.timeline-expansion-text code {{
  background: var(--surface-2); padding: 1px 5px; border-radius: 3px;
  font-size: 0.82em; color: var(--text-2);
  font-family: 'SFMono-Regular', 'Cascadia Code', Consolas, monospace;
}}

/* ── Status Dropdown ───────────────────────────────────── */
.status-dropdown {{
  position: fixed; z-index: 1000; background: var(--surface);
  border: 1px solid var(--border-2); border-radius: var(--radius);
  box-shadow: var(--shadow-md); min-width: 150px; padding: 4px;
}}
.status-dropdown-item {{
  display: flex; align-items: center; gap: 8px; padding: 6px 12px;
  border-radius: 4px; cursor: pointer; font-size: 0.78rem; color: var(--text-2);
  transition: background 0.1s;
}}
.status-dropdown-item:hover {{ background: var(--surface-hover); color: var(--text); }}
.status-dropdown-item .check {{ width: 14px; font-size: 0.7rem; }}
.status-dropdown-item .swatch {{
  width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0;
}}

/* ── Empty Detail ──────────────────────────────────────── */
.empty-detail {{
  color: var(--text-3); font-size: 0.85rem; padding: 60px 24px; text-align: center;
}}

/* ── Animations ────────────────────────────────────────── */
@media (prefers-reduced-motion: no-preference) {{
  .detail-inner > * {{
    animation: fadeUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) backwards;
  }}
  .detail-inner > *:nth-child(1) {{ animation-delay: 0.03s; }}
  .detail-inner > *:nth-child(2) {{ animation-delay: 0.08s; }}
  .detail-inner > *:nth-child(3) {{ animation-delay: 0.13s; }}
  .detail-inner > *:nth-child(4) {{ animation-delay: 0.18s; }}
  .detail-inner > *:nth-child(5) {{ animation-delay: 0.23s; }}

  @keyframes fadeUp {{
    from {{ opacity: 0; transform: translateY(8px); }}
    to   {{ opacity: 1; transform: translateY(0); }}
  }}
}}

/* ── Responsive ────────────────────────────────────────── */
@media (max-width: 900px) {{
  .sidebar {{ width: 56px; }}
  .sidebar .sidebar-brand {{ opacity: 0; width: 0; }}
  .sidebar .sidebar-search {{ display: none; }}
  .sidebar .sidebar-filters {{ display: none; }}
  .sidebar .project-name-row {{ display: none; }}
  .sidebar .project-last-session {{ display: none; }}
  .sidebar .project-time {{ display: none; }}
  .sidebar .project-avatar {{ display: grid; }}
  .sidebar .project-item {{ padding: 6px 0; display: flex; justify-content: center; border-left: none; }}
  .sidebar .sidebar-toggle {{ margin: 0 auto; }}
  .sidebar .sidebar-toggle .chevron {{ transform: rotate(180deg); }}
  .sidebar .inactive-toggle {{ padding: 6px 0; justify-content: center; }}
  .sidebar .inactive-label {{ display: none; }}
  .sidebar .sidebar-footer {{ justify-content: center; padding: 12px 0; }}
  .sidebar .footer-label {{ display: none; }}
  .detail-inner {{ padding: 24px 20px; }}
}}
</style>
</head>
<body>
<div class="layout">
  <!-- ── Sidebar ── -->
  <div class="sidebar" id="sidebar">
    <div class="sidebar-header">
      <div class="sidebar-brand">
        <div class="sidebar-title">Session Report</div>
        <div class="sidebar-sub">Last {days} day{"s" if days != 1 else ""} &middot; {total_projects} project{"s" if total_projects != 1 else ""}</div>
      </div>
      <button class="sidebar-toggle" onclick="toggleSidebar()" title="Collapse sidebar">
        <span class="chevron">&laquo;</span>
      </button>
    </div>

    <div class="sidebar-search">
      <input type="text" class="search-input" placeholder="Search projects... (/)" oninput="searchProjects(this.value)">
    </div>

    <div class="project-list" id="projectList">
      {''.join(sidebar_items)}
    </div>

    <div class="sidebar-footer">
      {f'<label class="inactive-toggle"><input type="checkbox" checked onchange="toggleInactiveVisibility(this)" class="inactive-cb">{n_inactive_proj} inactive</label>' if n_inactive_proj > 0 else ''}
      <button class="theme-toggle-btn" onclick="toggleTheme()" title="Toggle theme" id="themeToggle"></button>
    </div>
  </div>

  <!-- ── Detail Panel ── -->
  <div class="detail">
    <div class="detail-inner" id="detailInner">
      {first_detail if first_detail else '<div class="empty-detail">No projects found in the last ' + str(days) + ' day(s).</div>'}
    </div>
  </div>
</div>

<script type="application/json" id="projects-data">{projects_json_str}</script>
<script type="application/json" id="status-corrections">{{}}</script>

<script>
/* ── Constants ─────────────────────────────── */
const STATUS_VAR = {{'in_progress':'progress','blocked':'blocked','handed_off':'handed','complete':'complete','unknown':'text-3','active':'progress','inactive':'text-3'}};
const STATUS_LABELS = {{'in_progress':'In Progress','blocked':'Blocked','handed_off':'Handed Off','complete':'Complete','unknown':'Unsummarized','active':'Active','inactive':'Inactive'}};
const STATUS_LIST = ['in_progress','blocked','handed_off','complete'];
const STATUS_COLORS = {{'in_progress':'--progress','blocked':'--blocked','handed_off':'--handed','complete':'--complete'}};

/* ── State ─────────────────────────────────── */
let currentProject = 0;
let projectsData = [];
try {{ projectsData = JSON.parse(document.getElementById('projects-data').textContent); }} catch(e) {{}}

/* ── Theme ─────────────────────────────────── */
const THEME_SVG_LIGHT = '<svg viewBox="0 0 120 60" width="44" height="22" xmlns="http://www.w3.org/2000/svg"><rect width="120" height="60" rx="30" fill="var(--text-3)"/><circle cx="34" cy="30" r="12" fill="var(--bg)"/><circle cx="41" cy="24" r="12" fill="var(--text-3)"/><circle cx="86" cy="30" r="18" fill="var(--bg)"/></svg>';
const THEME_SVG_DARK = '<svg viewBox="0 0 120 60" width="44" height="22" xmlns="http://www.w3.org/2000/svg"><rect width="120" height="60" rx="30" fill="var(--text-3)"/><circle cx="30" cy="30" r="20" fill="var(--bg)"/><g transform="translate(90,30)" stroke="var(--bg)" stroke-width="3" stroke-linecap="round"><circle cx="0" cy="0" r="8" fill="none"/><line x1="0" y1="-14" x2="0" y2="-18"/><line x1="0" y1="14" x2="0" y2="18"/><line x1="-14" y1="0" x2="-18" y2="0"/><line x1="14" y1="0" x2="18" y2="0"/><line x1="-9.9" y1="-9.9" x2="-12.75" y2="-12.75"/><line x1="9.9" y1="9.9" x2="12.75" y2="12.75"/><line x1="-9.9" y1="9.9" x2="-12.75" y2="12.75"/><line x1="9.9" y1="-9.9" x2="12.75" y2="-12.75"/></g></svg>';

function toggleTheme() {{
  const el = document.documentElement;
  const next = el.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
  el.setAttribute('data-theme', next);
  localStorage.setItem('sr-theme', next);
  updateThemeUI();
}}

function updateThemeUI() {{
  const isDark = document.documentElement.getAttribute('data-theme') !== 'light';
  const btn = document.getElementById('themeToggle');
  if (btn) btn.innerHTML = isDark ? THEME_SVG_DARK : THEME_SVG_LIGHT;
}}

/* ── Sidebar Toggle ────────────────────────── */
function toggleSidebar() {{
  const sb = document.getElementById('sidebar');
  sb.classList.toggle('collapsed');
  localStorage.setItem('sr-sidebar-collapsed', sb.classList.contains('collapsed'));
}}

/* ── Project Selection ─────────────────────── */
function selectProject(index) {{
  currentProject = index;
  document.querySelectorAll('.project-item').forEach(p => p.classList.remove('selected'));
  const item = document.querySelector('[data-project-index="' + index + '"]');
  if (item) item.classList.add('selected');
  renderProjectDetail(index);
}}

/* ── Render Project Detail (CORE) ──────────── */
function renderProjectDetail(index) {{
  const proj = projectsData[index];
  if (!proj) return;
  const el = document.getElementById('detailInner');
  const sv = STATUS_VAR[proj.status] || 'text-3';
  const label = STATUS_LABELS[proj.status] || proj.status;
  const badgeStyle = 'background:var(--' + sv + '-bg);color:var(--' + sv + ')';
  const first = proj.sessions && proj.sessions[0];

  // Project-level badge: Active/Inactive — with manual override dropdown
  let html = '<div class="detail-header"><div class="detail-top-row"><div>' +
    '<div class="detail-project-name">' + esc(proj.name) + '</div>' +
    '<div class="detail-project-path">' + esc(proj.short_path) + '</div>' +
    '</div>' +
    '<span class="detail-badge" style="' + badgeStyle + ';cursor:pointer" ' +
    'onclick="showProjectStatusDropdown(this,' + index + ',event)">' +
    label + ' <span class="dd">&#9660;</span></span>' +
    '</div></div>';

  if (first) {{
    // Summary sections
    html += '<div class="summary-sections">' + first.summary_html + '</div>';

    // Session meta
    html += '<div class="session-meta-row">' +
      '<span>' + esc(first.time_long) + '</span>' +
      '<span class="meta-dot"></span>' +
      '<span>' + first.msgs + ' messages</span>' +
      '<span class="meta-dot"></span>' +
      '<span>' + esc(first.duration) + '</span></div>';

    // Next steps
    if (first.next_steps_html) {{
      html += '<div class="next-steps"><div class="next-steps-label">Next Steps</div>' +
        first.next_steps_html + '</div>';
    }}
  }}

  // Recent sessions timeline
  const sessions = proj.sessions || [];
  const nAll = sessions.length;
  const nProg = sessions.filter(s => s.status === 'in_progress').length;
  const nComp = sessions.filter(s => s.status === 'complete').length;

  html += '<div class="recent-sessions"><div class="recent-header">' +
    '<div class="section-label" style="margin-bottom:0">Recent Sessions</div>' +
    '<div class="detail-filters">' +
    '<button class="detail-filter active" onclick="filterSessions(\\'all\\',this)">All ' + nAll + '</button>';
  if (nProg) html += '<button class="detail-filter" onclick="filterSessions(\\'in_progress\\',this)">In Progress ' + nProg + '</button>';
  if (nComp) html += '<button class="detail-filter" onclick="filterSessions(\\'complete\\',this)">Complete ' + nComp + '</button>';
  html += '</div></div><div class="session-timeline">';

  sessions.forEach(function(sess) {{
    const sSv = STATUS_VAR[sess.status] || 'text-3';
    const sLabel = STATUS_LABELS[sess.status] || sess.status;
    const sBadgeStyle = sess.status === 'unknown'
      ? 'color:var(--text-3);background:transparent;border:1px dashed var(--border)'
      : 'background:var(--' + sSv + '-bg);color:var(--' + sSv + ')';

    html += '<div class="timeline-item" data-status="' + sess.status + '" onclick="toggleTimeline(this)">' +
      '<div class="timeline-top">' +
      '<span class="timeline-title">' + esc(sess.title) + '</span>' +
      '<span class="timeline-badge" style="' + sBadgeStyle + '" ' +
      'onclick="showStatusDropdown(this,\\'' + escAttr(sess.session_id) + '\\',event)">' +
      sLabel + ' <span class="dd">&#9660;</span></span></div>' +
      '<div class="timeline-meta">' +
      '<span>' + esc(sess.time_str) + '</span>' +
      '<span class="meta-dot"></span>' +
      '<span>' + sess.msgs + ' msgs</span>' +
      '<span class="meta-dot"></span>' +
      '<span>' + esc(sess.duration) + '</span></div>' +
      '<div class="timeline-expansion"><div class="timeline-expansion-inner">' +
      '<div class="timeline-expansion-text">' + sess.summary_html + '</div>' +
      '</div></div></div>';
  }});

  html += '</div></div>';
  el.innerHTML = html;
}}

/* ── Helpers ───────────────────────────────── */
function esc(s) {{ if (!s) return ''; const d = document.createElement('div'); d.textContent = s; return d.innerHTML; }}
function escAttr(s) {{ return esc(s).replace(/'/g, '&#39;'); }}

/* ── Timeline Toggle ───────────────────────── */
function toggleTimeline(el) {{ el.classList.toggle('expanded'); }}
function toggleSummaryBlock(el) {{ el.classList.toggle('collapsed'); }}

/* ── Status Dropdown ───────────────────────── */
function showStatusDropdown(badgeEl, sessionId, event) {{
  event.stopPropagation();
  // Remove existing dropdown
  const existing = document.querySelector('.status-dropdown');
  if (existing) {{ existing.remove(); return; }}

  const rect = badgeEl.getBoundingClientRect();
  const dd = document.createElement('div');
  dd.className = 'status-dropdown';
  dd.style.top = (rect.bottom + 4) + 'px';
  dd.style.left = rect.left + 'px';

  // Determine current status from badge text
  const currentText = badgeEl.textContent.trim().replace(/\\s*\\u25be\\s*$/, '').replace(/\\s*\\u25bc\\s*$/, '');
  const currentStatus = Object.keys(STATUS_LABELS).find(k => STATUS_LABELS[k] === currentText) || 'unknown';

  STATUS_LIST.forEach(function(st) {{
    const item = document.createElement('div');
    item.className = 'status-dropdown-item';
    const check = currentStatus === st ? '\\u2713' : '';
    const colorVar = STATUS_COLORS[st] || '--text-3';
    item.innerHTML = '<span class="check">' + check + '</span>' +
      '<span class="swatch" style="background:var(' + colorVar + ')"></span>' +
      STATUS_LABELS[st];
    item.onclick = function(e) {{
      e.stopPropagation();
      applyStatusCorrection(sessionId, st, badgeEl);
      dd.remove();
    }};
    dd.appendChild(item);
  }});

  document.body.appendChild(dd);
  // Close on outside click
  setTimeout(function() {{
    document.addEventListener('click', function handler() {{
      dd.remove();
      document.removeEventListener('click', handler);
    }}, {{ once: true }});
  }}, 0);
}}

function applyStatusCorrection(sessionId, newStatus, badgeEl) {{
  // Update badge visually
  const sv = STATUS_VAR[newStatus] || 'text-3';
  const label = STATUS_LABELS[newStatus] || newStatus;
  if (newStatus === 'unknown') {{
    badgeEl.style.cssText = 'color:var(--text-3);background:transparent;border:1px dashed var(--border)';
  }} else {{
    badgeEl.style.cssText = 'background:var(--' + sv + '-bg);color:var(--' + sv + ')';
  }}
  badgeEl.innerHTML = label + ' <span class="dd">&#9660;</span>';

  // Store correction in localStorage
  let corrections = {{}};
  try {{ corrections = JSON.parse(localStorage.getItem('sr-corrections') || '{{}}'); }} catch(e) {{}}
  corrections[sessionId] = newStatus;
  localStorage.setItem('sr-corrections', JSON.stringify(corrections));

  // Update embedded script block
  const scriptEl = document.getElementById('status-corrections');
  if (scriptEl) scriptEl.textContent = JSON.stringify(corrections);

  // Update projects data
  projectsData.forEach(function(p) {{
    p.sessions.forEach(function(s) {{
      if (s.session_id === sessionId) s.status = newStatus;
    }});
  }});
}}

/* ── Project Status Override ──────────────── */
function showProjectStatusDropdown(badgeEl, projectIndex, event) {{
  event.stopPropagation();
  const existing = document.querySelector('.status-dropdown');
  if (existing) {{ existing.remove(); return; }}

  const rect = badgeEl.getBoundingClientRect();
  const dd = document.createElement('div');
  dd.className = 'status-dropdown';
  dd.style.top = (rect.bottom + 4) + 'px';
  dd.style.left = rect.left + 'px';

  const proj = projectsData[projectIndex];
  const currentStatus = proj ? proj.status : 'active';

  ['active', 'inactive'].forEach(function(st) {{
    const item = document.createElement('div');
    item.className = 'status-dropdown-item';
    const check = currentStatus === st ? '\\u2713' : '';
    const colorVar = STATUS_COLORS[st] || (st === 'active' ? '--progress' : '--text-3');
    item.innerHTML = '<span class="check">' + check + '</span>' +
      '<span class="swatch" style="background:var(' + colorVar + ')"></span>' +
      STATUS_LABELS[st];
    item.onclick = function(e) {{
      e.stopPropagation();
      applyProjectStatusOverride(projectIndex, st, badgeEl);
      dd.remove();
    }};
    dd.appendChild(item);
  }});

  document.body.appendChild(dd);
  setTimeout(function() {{
    document.addEventListener('click', function handler() {{
      dd.remove();
      document.removeEventListener('click', handler);
    }}, {{ once: true }});
  }}, 0);
}}

function applyProjectStatusOverride(projectIndex, newStatus, badgeEl) {{
  const proj = projectsData[projectIndex];
  if (!proj) return;
  proj.status = newStatus;

  const sv = STATUS_VAR[newStatus] || 'text-3';
  const label = STATUS_LABELS[newStatus] || newStatus;
  badgeEl.style.cssText = 'background:var(--' + sv + '-bg);color:var(--' + sv + ');cursor:pointer';
  badgeEl.innerHTML = label + ' <span class="dd">&#9660;</span>';

  // Update sidebar item
  const sidebarItem = document.querySelector('.project-item[data-project-index="' + projectIndex + '"]');
  if (sidebarItem) {{
    sidebarItem.dataset.status = newStatus;
    sidebarItem.classList.toggle('inactive', newStatus === 'inactive');
    const badge = sidebarItem.querySelector('.project-status');
    if (badge) {{
      if (newStatus === 'inactive') {{
        badge.style.cssText = '';
        badge.className = 'project-status project-status-inactive';
      }} else {{
        badge.style.cssText = 'background:var(--' + sv + '-bg);color:var(--' + sv + ')';
        badge.className = 'project-status';
      }}
      badge.textContent = label;
    }}
  }}

  // Store in localStorage
  let overrides = {{}};
  try {{ overrides = JSON.parse(localStorage.getItem('sr-project-overrides') || '{{}}'); }} catch(e) {{}}
  overrides[proj.folder] = newStatus;
  localStorage.setItem('sr-project-overrides', JSON.stringify(overrides));
}}

/* ── Toggle Inactive Visibility ───────────── */
function toggleInactiveVisibility(cb) {{
  const items = document.querySelectorAll('.project-item.inactive');
  const show = cb ? cb.checked : !(items.length > 0 && items[0].classList.contains('sr-hidden'));
  items.forEach(function(el) {{ el.classList.toggle('sr-hidden', !show); }});
  const checkbox = document.querySelector('.inactive-cb');
  if (checkbox) checkbox.checked = show;
  localStorage.setItem('sr-hide-inactive', show ? '' : '1');
}}

/* ── Filter Sessions (detail timeline) ─────── */
function filterSessions(status, btn) {{
  const container = btn.closest('.recent-sessions');
  if (!container) return;
  container.querySelectorAll('.detail-filter').forEach(c => c.classList.remove('active'));
  btn.classList.add('active');

  container.querySelectorAll('.timeline-item').forEach(function(item) {{
    if (status === 'all' || item.dataset.status === status) {{
      item.classList.remove('filter-hidden');
    }} else {{
      item.classList.add('filter-hidden');
    }}
  }});
}}

/* ── Search Projects ───────────────────────── */
function searchProjects(query) {{
  const q = query.toLowerCase().trim();
  document.querySelectorAll('.project-item').forEach(function(item) {{
    if (!q) {{ item.style.display = ''; return; }}
    const text = item.textContent.toLowerCase();
    item.style.display = text.includes(q) ? '' : 'none';
  }});
  // Hide divider when searching
  const divider = document.getElementById('inactiveDivider');
  if (divider) divider.style.display = q ? 'none' : '';
}}


/* ── Initialization ────────────────────────── */
(function init() {{
  // Theme
  const saved = localStorage.getItem('sr-theme');
  const pref = saved || (matchMedia('(prefers-color-scheme:light)').matches ? 'light' : 'dark');
  document.documentElement.setAttribute('data-theme', pref);
  updateThemeUI();

  // Sidebar collapsed state
  const collapsed = localStorage.getItem('sr-sidebar-collapsed');
  if (collapsed === 'true') {{
    document.getElementById('sidebar').classList.add('collapsed');
  }}

  // Auto-collapse on narrow screens
  if (window.innerWidth < 900) {{
    document.getElementById('sidebar').classList.add('collapsed');
  }}

  // Load corrections from localStorage and merge
  let corrections = {{}};
  try {{ corrections = JSON.parse(localStorage.getItem('sr-corrections') || '{{}}'); }} catch(e) {{}}
  if (Object.keys(corrections).length > 0) {{
    const scriptEl = document.getElementById('status-corrections');
    // Merge with embedded corrections
    let embedded = {{}};
    try {{ embedded = JSON.parse(scriptEl.textContent || '{{}}'); }} catch(e) {{}}
    Object.assign(embedded, corrections);
    scriptEl.textContent = JSON.stringify(embedded);
    // Apply corrections to data
    projectsData.forEach(function(p) {{
      p.sessions.forEach(function(s) {{
        if (corrections[s.session_id]) s.status = corrections[s.session_id];
      }});
    }});
  }}

  // Restore inactive visibility preference
  if (localStorage.getItem('sr-hide-inactive') === '1') {{
    document.querySelectorAll('.project-item.inactive').forEach(function(el) {{ el.classList.add('sr-hidden'); }});
    const cb = document.querySelector('.inactive-cb');
    if (cb) cb.checked = false;
  }}

  // Select first project
  if (projectsData.length > 0) {{
    // Already rendered server-side, just ensure state is correct
    currentProject = 0;
  }}
}})();

/* ── Keyboard Shortcuts ────────────────────── */
document.addEventListener('keydown', function(e) {{
  const search = document.querySelector('.search-input');
  if (!search) return;
  const active = document.activeElement;
  const isInput = active && (active.tagName === 'INPUT' || active.tagName === 'SELECT' || active.tagName === 'TEXTAREA');
  if ((e.key === '/' && !isInput) || (e.key === 'k' && (e.ctrlKey || e.metaKey))) {{
    e.preventDefault();
    search.focus();
  }}
  if (e.key === 'Escape') {{
    if (active === search && search.value) {{
      search.value = '';
      searchProjects('');
      search.blur();
    }}
  }}
}});
</script>
</body>
</html>"""
    return html


# ─── Text output (terminal) ──────────────────────────────────────────────────


def print_text_report(all_sessions, summaries, days):
    by_project = defaultdict(list)
    for s in all_sessions:
        by_project[s["cwd"] or s["project_path"]].append(s)

    print(f"Found {len(all_sessions)} active session(s) across {len(by_project)} folder(s)\n")

    for folder, sessions in sorted(
        by_project.items(), key=lambda x: max(s["latest"] for s in x[1]), reverse=True
    ):
        sf = short_path(folder)
        print(f"{'─'*80}")
        print(f"  FOLDER: {sf}")
        print(f"  Sessions: {len(sessions)}")
        print(f"{'─'*80}")

        for i, s in enumerate(sessions, 1):
            sid = s["session_id"]
            s_data = summaries.get(sid, {})
            status = s_data.get("status", "unknown") if isinstance(s_data, dict) else "unknown"
            status_label = STATUS_LABELS.get(status, status).upper()

            print(f"\n  [{status_label}] Session {i}/{len(sessions)}  [{sid[:8]}...]")
            print(f"  Started:  {format_timestamp(s['earliest'])}")
            print(f"  Latest:   {format_timestamp(s['latest'])}")
            print(f"  Messages: {s['total_messages']} total ({s['user_msg_count']} user, {s['assistant_msg_count']} assistant)")

            summary = s_data.get("summary", "") if isinstance(s_data, dict) else (s_data if isinstance(s_data, str) else "")
            if summary and not summary.startswith("("):
                print(f"\n{summary}")
            else:
                print(f"\n  OPENING ASK:")
                print(f"    {truncate(s['first_ask'], 200)}")
                if len(s["topics"]) > 1:
                    print(f"\n  TOPICS ({len(s['topics'])} user prompts):")
                    show = s["topics"]
                    if len(show) > 8:
                        for t in show[:5]:
                            print(f"    - {t}")
                        print(f"    ... ({len(show) - 7} more) ...")
                        for t in show[-2:]:
                            print(f"    - {t}")
                    else:
                        for t in show:
                            print(f"    - {t}")
                print(f"\n  WHAT'S NEXT:")
                if s["last_user"]:
                    clean = clean_user_text(s["last_user"])
                    if clean:
                        print(f"    Last ask: {truncate(clean, 200)}")
                if s["last_assistant"]:
                    text = clean_transcript_text(s["last_assistant"])
                    if text and len(text) > 10:
                        print(f"    Last response: {truncate(text, 200)}")
            print()

    total_msgs = sum(s["total_messages"] for s in all_sessions)
    total_user = sum(s["user_msg_count"] for s in all_sessions)
    print(f"\n{'='*80}")
    print(f"  SUMMARY")
    print(f"{'='*80}")
    print(f"  Total sessions:  {len(all_sessions)}")
    print(f"  Total messages:  {total_msgs} ({total_user} user prompts)")
    print(f"  Active folders:  {len(by_project)}")
    print(f"\n  Most active folders:")
    folder_activity = sorted(by_project.items(), key=lambda x: sum(s["total_messages"] for s in x[1]), reverse=True)
    for folder, sessions in folder_activity[:10]:
        msg_count = sum(s["total_messages"] for s in sessions)
        sf = short_path(folder)
        print(f"    {sf:<50} {len(sessions):>2} session(s), {msg_count:>5} msgs")
    print()


# ─── Main ─────────────────────────────────────────────────────────────────────


def cleanup_old_reports(keep=10):
    if not REPORT_DIR.exists():
        return
    reports = sorted(REPORT_DIR.glob("session-report-*.html"), key=lambda f: f.stat().st_mtime, reverse=True)
    for old in reports[keep:]:
        try:
            old.unlink()
        except OSError:
            pass
    removed = len(reports) - min(len(reports), keep)
    if removed > 0:
        print(f"  Cleaned up {removed} old report(s)")


def normalize_args(argv):
    normalized = []
    bare_words = {
        "text": "--text", "refresh": "--refresh", "no-ai": "--no-ai",
        "no-open": "--no-open", "collect": "--collect",
        "review-statuses": "--review-statuses",
    }
    for arg in argv:
        normalized.append(bare_words.get(arg.lower(), arg))
    return normalized


def main():
    parser = argparse.ArgumentParser(description="Claude Code Session Reporter")
    parser.add_argument("days", nargs="?", type=int, default=3, help="Days to look back (default: 3)")
    parser.add_argument("--no-ai", action="store_true", help="Ignore cached summaries, show raw output")
    parser.add_argument("--refresh", action="store_true", help="With --collect: include all sessions regardless of cache")
    parser.add_argument("--text", action="store_true", help="Terminal text output instead of HTML")
    parser.add_argument("--no-open", action="store_true", help="Generate HTML but don't open browser")
    parser.add_argument("--limit", type=int, default=0, help="Max sessions to scan (0 = unlimited)")
    parser.add_argument("--collect", action="store_true", help="Output JSON of sessions needing summaries")
    parser.add_argument("--collect-file", type=str, default=None, help="Path for collect output")
    parser.add_argument("--max-collect", type=int, default=0, help="Max sessions to collect for summarization (0 = unlimited)")
    parser.add_argument("--update-cache", type=str, default=None, metavar="FILE", help="Merge summaries from a JSON file into the cache")
    parser.add_argument("--review-statuses", action="store_true", help="Output folder-grouped summaries for cross-session status review")
    parser.add_argument("--update-statuses", type=str, default=None, metavar="FILE", help="Apply status corrections from a JSON file")
    args = parser.parse_args(normalize_args(sys.argv[1:]))

    if args.update_cache:
        print("Updating summary cache...")
        update_cache_from_file(args.update_cache)
        return

    if args.update_statuses:
        print("Applying status corrections...")
        update_statuses_from_file(args.update_statuses)
        return

    days = args.days
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    # Apply any status corrections from previous report
    corrections = read_corrections_from_previous_report()
    apply_corrections_to_cache(corrections)

    print(f"\n{'='*80}")
    print(f"  CLAUDE CODE SESSION REPORT - Last {days} day(s)")
    print(f"  Generated: {datetime.now().strftime('%Y-%m-%d %I:%M %p')}")
    print(f"{'='*80}\n")

    all_sessions = collect_sessions(days)
    if not all_sessions:
        print(f"No sessions with activity in the last {days} day(s).\n")
        if args.collect:
            output_path = args.collect_file or str(REPORT_DIR / "_collect.json")

            with open(output_path, "w", encoding="utf-8") as f:
                json.dump({"sessions": [], "total_found": 0, "already_cached": 0, "too_short": 0, "needs_summary": 0}, f)
            print(f"  Collect output: {output_path}")
        return

    if args.limit > 0 and len(all_sessions) > args.limit:
        print(f"  Limiting to {args.limit} most recent sessions (of {len(all_sessions)} found)")
        all_sessions = all_sessions[: args.limit]

    if args.collect:
        data = collect_for_summarization(all_sessions, args.max_collect, args.refresh)
        output_path = args.collect_file or str(REPORT_DIR / "_collect.json")
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"  Total sessions found: {data['total_found']}")
        print(f"  Already cached: {data['already_cached']}")
        print(f"  Too short for summary: {data['too_short']}")
        print(f"  Needs summarization: {data['needs_summary']}")
        if data['needs_summary'] < data['total_found'] - data['already_cached'] - data['too_short']:
            print(f"  (capped at --max-collect {args.max_collect}; run again for more)")
        print(f"  Collect output: {output_path}")
        return

    if args.review_statuses:
        summaries = load_cached_summaries(all_sessions, False)
        data = prepare_review_data(all_sessions, summaries)
        output_path = str(REPORT_DIR / "_review.json")
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"  Folders needing cross-session review: {data['needs_review']}")
        print(f"  Review output: {output_path}")
        return

    summaries = load_cached_summaries(all_sessions, args.no_ai)

    if args.text:
        print_text_report(all_sessions, summaries, days)
    else:
        html = generate_html(all_sessions, summaries, days)
        report_file = REPORT_DIR / f"session-report-{datetime.now().strftime('%Y%m%d-%H%M%S')}.html"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(html)
        cleanup_old_reports(keep=10)
        print(f"Report saved: {report_file}")
        if not args.no_open:
            webbrowser.open(str(report_file))
            print("Opened in browser.")


if __name__ == "__main__":
    main()
