#!/usr/bin/env python
"""
Claude Code Session Reporter
Scans all Claude Code sessions for recent activity and produces concise
reports of what was accomplished, where things left off, etc.

Summaries are generated by Claude Code itself via the /session-report slash
command, which orchestrates: collect -> summarize -> cache -> render.
This script handles data collection, caching, and rendering only.

Works on Windows, macOS, and Linux — reads from ~/.claude/ which is the same
structure on all platforms.

Usage:
    python claude-session-report.py [days]              # default: 3 days, HTML
    python claude-session-report.py 7                   # last 7 days
    python claude-session-report.py 1 --text            # terminal text output
    python claude-session-report.py 3 --no-ai           # ignore cached summaries
    python claude-session-report.py 3 --limit 20        # only process 20 most recent sessions
    python claude-session-report.py 7 text              # bare words work too (no -- needed)

    # Used by the /session-report slash command:
    python claude-session-report.py 3 --collect         # output sessions needing summaries
    python claude-session-report.py --update-cache F    # merge summaries from JSON file F
    python claude-session-report.py 3 --review-statuses # output folder-grouped summaries for status review
    python claude-session-report.py --update-statuses F # apply status corrections from JSON file F
"""

import json
import os
import sys
import re
import argparse
import tempfile
import webbrowser
from datetime import datetime, timedelta, timezone
from pathlib import Path
from collections import defaultdict
from html import escape as html_escape

# Fix Windows console encoding
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

CLAUDE_DIR = Path.home() / ".claude"
PROJECTS_DIR = CLAUDE_DIR / "projects"
SESSIONS_DIR = CLAUDE_DIR / "sessions"
HISTORY_FILE = CLAUDE_DIR / "history.jsonl"
CACHE_FILE = CLAUDE_DIR / "session-report-cache.json"
REPORT_DIR = CLAUDE_DIR / "reports"
HOME_STR = str(Path.home())

MIN_MESSAGES_FOR_AI = 4

STATUS_LABELS = {
    "in_progress": "In Progress",
    "blocked": "Blocked",
    "handed_off": "Handed Off",
    "complete": "Complete",
    "unknown": "Unsummarized",
}
STATUS_ORDER = {"blocked": 0, "in_progress": 1, "handed_off": 2, "unknown": 3, "complete": 4}


# ─── Cache ────────────────────────────────────────────────────────────────────


def load_summary_cache() -> dict:
    if not CACHE_FILE.exists():
        return {}
    try:
        with open(CACHE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def save_summary_cache(cache: dict) -> bool:
    try:
        fd, tmp_path = tempfile.mkstemp(dir=CACHE_FILE.parent, suffix=".tmp")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)
        Path(tmp_path).replace(CACHE_FILE)
        return True
    except OSError as e:
        print(f"  WARNING: Failed to write cache: {e}")
        return False


def get_cached_data(cache, session_id, msg_count, latest_ts):
    """Return dict with summary/status/title from cache, or None on miss."""
    entry = cache.get(session_id)
    if not entry:
        return None
    summary = entry.get("summary", "")
    if not summary or summary.startswith("(Haiku summary failed") or summary.startswith("(error"):
        return None
    if entry.get("msg_count") == msg_count and entry.get("latest_ts") == latest_ts:
        return {
            "summary": summary,
            "status": entry.get("status", "unknown"),
            "title": entry.get("title", ""),
        }
    return None


# ─── Helpers ──────────────────────────────────────────────────────────────────


def clean_transcript_text(text):
    """Strip XML command tags and other noise from message text."""
    if not text:
        return ""
    text = re.sub(r'<command-name>.*?</command-name>', '', text, flags=re.DOTALL)
    text = re.sub(r'<command-message>.*?</command-message>', '', text, flags=re.DOTALL)
    text = re.sub(r'<command-args>.*?</command-args>', '', text, flags=re.DOTALL)
    text = re.sub(r'<local-command-caveat>.*?</local-command-caveat>', '', text, flags=re.DOTALL)
    text = re.sub(r'<system-reminder>.*?</system-reminder>', '', text, flags=re.DOTALL)
    text = re.sub(r'<task-notification>.*?</task-notification>', '', text, flags=re.DOTALL)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def truncate(text, max_len=120):
    text = text.replace("\n", " ").strip()
    return text if len(text) <= max_len else text[: max_len - 3] + "..."


def format_timestamp(ts):
    if not ts:
        return "unknown"
    local = ts.astimezone()
    now = datetime.now(timezone.utc).astimezone()
    if local.date() == now.date():
        return f"Today {local.strftime('%I:%M %p')}"
    elif local.date() == (now - timedelta(days=1)).date():
        return f"Yesterday {local.strftime('%I:%M %p')}"
    else:
        return local.strftime("%b %d %I:%M %p")


def format_timestamp_short(ts):
    if not ts:
        return ""
    local = ts.astimezone()
    now = datetime.now(timezone.utc).astimezone()
    if local.date() == now.date():
        return f"Today {local.strftime('%I:%M %p')}"
    elif local.date() == (now - timedelta(days=1)).date():
        return "Yesterday"
    else:
        return local.strftime("%b %d")


def short_path(folder):
    if folder.startswith(HOME_STR):
        return "~" + folder[len(HOME_STR):]
    return folder


def clean_user_text(text):
    text = text.strip()
    if not text or len(text) < 5:
        return None
    for p in ("[tool result", "[Request interrupted", "<task-notification",
              "<command-", "<local-command", "# Screenshot"):
        if text.startswith(p):
            return None
    if text.startswith("This session is being continued"):
        return "(continued from previous session)"
    return text


def extract_title_from_summary(summary):
    """Extract a short title from the first sentence after ## Summary."""
    if not summary:
        return None
    lines = summary.split("\n")
    found = False
    for line in lines:
        stripped = line.strip()
        if stripped.lower().startswith("## summary"):
            found = True
            continue
        if found and stripped and not stripped.startswith("#"):
            sentence = stripped.split(". ")[0]
            if len(sentence) > 80:
                sentence = sentence[:77] + "..."
            return sentence
    return None


# ─── Session parsing ─────────────────────────────────────────────────────────


def decode_project_path(encoded: str) -> str:
    parts = encoded.split("--")
    if sys.platform == "win32":
        if parts and len(parts[0]) == 1 and parts[0].isalpha():
            drive = parts[0] + ":"
            return drive + "\\" + "\\".join(parts[1:])
        return "\\".join(parts)
    else:
        if encoded.startswith("--"):
            return "/" + "/".join(parts[1:])
        if parts and len(parts[0]) == 1 and parts[0].isalpha():
            return parts[0] + ":/" + "/".join(parts[1:])
        return "/".join(parts)


def extract_text_from_content(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts = []
        for block in content:
            if isinstance(block, dict):
                if block.get("type") == "text":
                    texts.append(block.get("text", ""))
                elif block.get("type") == "tool_use":
                    texts.append(f"[tool: {block.get('name', '')}]")
            elif isinstance(block, str):
                texts.append(block)
        return " ".join(texts)
    return str(content)


def parse_session_file(filepath):
    messages = []
    session_id = None
    cwd = None
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                entry_type = entry.get("type")
                if entry_type not in ("user", "assistant"):
                    continue
                if not session_id:
                    session_id = entry.get("sessionId")
                if not cwd:
                    cwd = entry.get("cwd")
                timestamp_str = entry.get("timestamp")
                timestamp = None
                if timestamp_str:
                    try:
                        if isinstance(timestamp_str, str):
                            timestamp = datetime.fromisoformat(timestamp_str.replace("Z", "+00:00"))
                        elif isinstance(timestamp_str, (int, float)):
                            timestamp = datetime.fromtimestamp(timestamp_str / 1000, tz=timezone.utc)
                    except (ValueError, OSError):
                        pass
                msg = entry.get("message", {})
                role = msg.get("role", entry_type)
                content = msg.get("content", "")
                text = extract_text_from_content(content)
                if text and text.strip():
                    messages.append({"role": role, "text": text.strip(), "timestamp": timestamp})
    except (OSError, PermissionError):
        return None
    if not messages:
        return None
    return {"session_id": session_id or filepath.stem, "cwd": cwd, "messages": messages}


def get_session_cwd_from_sessions_dir():
    mapping = {}
    if not SESSIONS_DIR.exists():
        return mapping
    for f in SESSIONS_DIR.glob("*.json"):
        try:
            with open(f, "r", encoding="utf-8", errors="replace") as fh:
                data = json.loads(fh.read())
                sid = data.get("sessionId")
                cwd = data.get("cwd")
                if sid and cwd:
                    mapping[sid] = cwd
        except (json.JSONDecodeError, OSError):
            pass
    return mapping


def get_history_sessions():
    sessions = defaultdict(lambda: {"project": None})
    if not HISTORY_FILE.exists():
        return sessions
    try:
        with open(HISTORY_FILE, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                try:
                    entry = json.loads(line.strip())
                    sid = entry.get("sessionId")
                    if sid and entry.get("project"):
                        sessions[sid]["project"] = entry["project"]
                except json.JSONDecodeError:
                    continue
    except OSError:
        pass
    return sessions


# ─── Collect sessions ────────────────────────────────────────────────────────


def collect_sessions(days):
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    history_sessions = get_history_sessions()
    session_cwd_map = get_session_cwd_from_sessions_dir()
    all_sessions = []

    if not PROJECTS_DIR.exists():
        return all_sessions

    print("Scanning sessions...", end="", flush=True)

    for project_dir in sorted(PROJECTS_DIR.iterdir()):
        if not project_dir.is_dir():
            continue
        project_path = decode_project_path(project_dir.name)

        for session_file in project_dir.glob("*.jsonl"):
            try:
                mtime = datetime.fromtimestamp(session_file.stat().st_mtime, tz=timezone.utc)
                if mtime < cutoff:
                    continue
            except OSError:
                continue

            data = parse_session_file(session_file)
            if not data or not data["messages"]:
                continue

            timestamps = [m["timestamp"] for m in data["messages"] if m["timestamp"]]
            if not timestamps:
                continue
            latest = max(timestamps)
            earliest = min(timestamps)
            if latest < cutoff:
                continue

            cwd = data["cwd"]
            sid = data["session_id"]
            if not cwd and sid in session_cwd_map:
                cwd = session_cwd_map[sid]
            if not cwd and sid in history_sessions:
                cwd = history_sessions[sid]["project"]
            if not cwd:
                cwd = project_path

            user_msgs = [m for m in data["messages"] if m["role"] == "user"]
            assistant_msgs = [m for m in data["messages"] if m["role"] == "assistant"]

            topics = []
            for m in user_msgs:
                clean = clean_user_text(m["text"])
                if clean:
                    topics.append(truncate(clean, 100))

            first_ask = topics[0] if topics else (
                truncate(clean_transcript_text(user_msgs[0]["text"]), 200) if user_msgs else "N/A"
            )

            last_user = last_assistant = None
            for m in reversed(data["messages"]):
                if m["role"] == "user" and not last_user:
                    last_user = m["text"]
                if m["role"] == "assistant" and not last_assistant:
                    last_assistant = m["text"]
                if last_user and last_assistant:
                    break

            all_sessions.append({
                "session_id": sid,
                "cwd": cwd,
                "project_path": project_path,
                "earliest": earliest,
                "latest": latest,
                "user_msg_count": len(user_msgs),
                "assistant_msg_count": len(assistant_msgs),
                "total_messages": len(data["messages"]),
                "first_ask": first_ask,
                "topics": topics,
                "last_user": last_user,
                "last_assistant": last_assistant,
                "raw_messages": data["messages"],
            })
            print(".", end="", flush=True)

    print(f" done! ({len(all_sessions)} sessions found)\n")
    all_sessions.sort(key=lambda s: s["latest"], reverse=True)
    return all_sessions


# ─── Transcript sampling ─────────────────────────────────────────────────────


def prepare_transcript(session_data):
    messages = session_data.get("raw_messages", [])
    if len(messages) <= 20:
        sampled = messages
    else:
        first = messages[:6]
        last = messages[-6:]
        mid_start = len(messages) // 3
        mid_end = 2 * len(messages) // 3
        middle = messages[mid_start : mid_start + 4] + messages[mid_end : mid_end + 4]
        sampled = (
            first
            + [{"role": "system", "text": f"... ({len(messages) - 20} messages omitted) ..."}]
            + middle
            + last
        )

    transcript_parts = []
    for m in sampled:
        text = clean_transcript_text(m["text"][:500])
        if not text or len(text) < 5:
            continue
        if text.startswith("[tool result") or text.startswith("[tool:"):
            continue
        transcript_parts.append(f"{m['role'].upper()}: {text}")

    transcript = "\n".join(transcript_parts)[:12000]
    return transcript


# ─── Summaries ────────────────────────────────────────────────────────────────


def load_cached_summaries(all_sessions, no_ai=False):
    """Load cached summaries. Returns {session_id: {summary, status, title}}."""
    if no_ai:
        return {}
    cache = load_summary_cache()
    summaries = {}
    cached_count = 0
    for s in all_sessions:
        sid = s["session_id"]
        latest_ts = s["latest"].isoformat() if s["latest"] else ""
        cached = get_cached_data(cache, sid, s["total_messages"], latest_ts)
        if cached:
            summaries[sid] = cached
            cached_count += 1
    if cached_count:
        print(f"  {cached_count} session(s) loaded from summary cache")
    return summaries


def collect_for_summarization(all_sessions, max_collect, refresh):
    cache = {} if refresh else load_summary_cache()
    results = []
    skipped = 0
    already_cached = 0

    for s in all_sessions:
        sid = s["session_id"]
        if s["total_messages"] < MIN_MESSAGES_FOR_AI:
            skipped += 1
            continue
        latest_ts = s["latest"].isoformat() if s["latest"] else ""
        if not refresh:
            cached = get_cached_data(cache, sid, s["total_messages"], latest_ts)
            if cached:
                already_cached += 1
                continue

        transcript = prepare_transcript(s)
        if len(transcript.strip()) < 50:
            skipped += 1
            continue

        results.append({
            "session_id": sid,
            "cwd": s.get("cwd", "unknown"),
            "msg_count": s["total_messages"],
            "latest_ts": latest_ts,
            "folder": s.get("cwd", s.get("project_path", "")),
            "transcript": transcript,
        })

        if max_collect > 0 and len(results) >= max_collect:
            break

    return {
        "sessions": results,
        "total_found": len(all_sessions),
        "already_cached": already_cached,
        "too_short": skipped,
        "needs_summary": len(results),
    }


def update_cache_from_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            new_entries = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"Error reading summaries file: {e}")
        return False

    cache = load_summary_cache()
    merged = 0
    for sid, entry in new_entries.items():
        if not isinstance(entry, dict) or "summary" not in entry:
            print(f"  Skipping {sid}: missing 'summary' field")
            continue
        cache[sid] = {
            "summary": entry["summary"],
            "status": entry.get("status", "unknown"),
            "title": entry.get("title", ""),
            "msg_count": entry.get("msg_count"),
            "latest_ts": entry.get("latest_ts", ""),
            "folder": entry.get("folder", ""),
        }
        merged += 1

    if not save_summary_cache(cache):
        return False
    print(f"  Merged {merged} summary(ies) into cache")
    return True


# ─── Two-pass status review ──────────────────────────────────────────────────


def prepare_review_data(all_sessions, summaries):
    """Group sessions by folder with their cached summaries for cross-session status review."""
    by_folder = defaultdict(list)
    for s in all_sessions:
        sid = s["session_id"]
        s_data = summaries.get(sid, {})
        if not isinstance(s_data, dict) or not s_data.get("summary"):
            continue
        by_folder[s["cwd"] or s["project_path"]].append({
            "session_id": sid,
            "title": s_data.get("title", ""),
            "status": s_data.get("status", "unknown"),
            "summary": s_data["summary"],
            "latest_ts": s["latest"].isoformat() if s["latest"] else "",
        })

    folders = []
    for folder, sessions in sorted(by_folder.items()):
        if len(sessions) > 1:
            sessions.sort(key=lambda x: x["latest_ts"])
            folders.append({
                "folder": folder,
                "session_count": len(sessions),
                "sessions": sessions,
            })

    return {
        "folders": folders,
        "needs_review": len(folders),
    }


def update_statuses_from_file(filepath):
    """Update only the status field for existing cache entries."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            corrections = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"Error reading status corrections: {e}")
        return False

    cache = load_summary_cache()
    updated = 0
    for sid, entry in corrections.items():
        if sid not in cache:
            print(f"  Skipping {sid}: not in cache")
            continue
        new_status = entry.get("status") if isinstance(entry, dict) else entry
        if new_status and new_status in STATUS_LABELS:
            old_status = cache[sid].get("status", "unknown")
            if old_status != new_status:
                cache[sid]["status"] = new_status
                updated += 1

    if updated > 0:
        if not save_summary_cache(cache):
            return False
    print(f"  Updated {updated} session status(es)")
    return True


# ─── Markdown conversion ─────────────────────────────────────────────────────


def md_to_html(text):
    lines = text.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()
        if in_list and not stripped.startswith("- ") and not stripped.startswith("* "):
            html_lines.append("</ul>")
            in_list = False
        if stripped.startswith("## "):
            html_lines.append(f"<h3>{html_escape(stripped[3:])}</h3>")
        elif stripped.startswith("# "):
            html_lines.append(f"<h2>{html_escape(stripped[2:])}</h2>")
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            content = html_escape(stripped[2:])
            content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', content)
            content = re.sub(r'`(.+?)`', r'<code>\1</code>', content)
            html_lines.append(f"<li>{content}</li>")
        elif stripped == "":
            continue
        else:
            content = html_escape(stripped)
            content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', content)
            content = re.sub(r'`(.+?)`', r'<code>\1</code>', content)
            html_lines.append(f"<p>{content}</p>")

    if in_list:
        html_lines.append("</ul>")
    return "\n".join(html_lines)


# ─── HTML output ──────────────────────────────────────────────────────────────


def generate_html(all_sessions, summaries, days):
    by_project = defaultdict(list)
    status_counts = defaultdict(int)

    for s in all_sessions:
        sid = s["session_id"]
        s_data = summaries.get(sid, {})
        if isinstance(s_data, dict):
            s["_summary"] = s_data.get("summary", "")
            s["_status"] = s_data.get("status", "unknown")
            s["_title"] = s_data.get("title") or extract_title_from_summary(s_data.get("summary", ""))
        else:
            s["_summary"] = ""
            s["_status"] = "unknown"
            s["_title"] = None

        if not s["_title"]:
            s["_title"] = truncate(s["first_ask"], 80)

        status_counts[s["_status"]] += 1
        by_project[s["cwd"] or s["project_path"]].append(s)

    total_msgs = sum(s["total_messages"] for s in all_sessions)
    now_str = datetime.now().strftime("%b %d, %Y %I:%M %p")
    n_progress = status_counts.get("in_progress", 0)
    n_blocked = status_counts.get("blocked", 0)
    n_handed = status_counts.get("handed_off", 0)
    n_complete = status_counts.get("complete", 0)
    n_unknown = status_counts.get("unknown", 0)

    sorted_folders = sorted(
        by_project.items(), key=lambda x: max(s["latest"] for s in x[1]), reverse=True
    )

    # Build folder HTML
    folder_parts = []
    for folder, sessions in sorted_folders:
        sf = short_path(folder)
        latest_ts = format_timestamp_short(max(s["latest"] for s in sessions))
        total_folder_msgs = sum(s["total_messages"] for s in sessions)

        # Folder status counts
        f_counts = defaultdict(int)
        for s in sessions:
            f_counts[s["_status"]] += 1

        folder_status_pills = ""
        if f_counts.get("in_progress", 0):
            n = f_counts["in_progress"]
            folder_status_pills += f'<span class="fpill progress" title="{n} in progress">{n}</span>'
        if f_counts.get("blocked", 0):
            n = f_counts["blocked"]
            folder_status_pills += f'<span class="fpill blocked" title="{n} blocked">{n}</span>'
        if f_counts.get("handed_off", 0):
            n = f_counts["handed_off"]
            folder_status_pills += f'<span class="fpill handed" title="{n} handed off">{n}</span>'

        # Status breakdown for folder info
        status_parts = []
        if f_counts.get("in_progress", 0):
            status_parts.append(f'{f_counts["in_progress"]} active')
        if f_counts.get("blocked", 0):
            status_parts.append(f'{f_counts["blocked"]} blocked')
        if f_counts.get("handed_off", 0):
            status_parts.append(f'{f_counts["handed_off"]} handed off')
        if f_counts.get("complete", 0):
            status_parts.append(f'{f_counts["complete"]} complete')
        if f_counts.get("unknown", 0):
            status_parts.append(f'{f_counts["unknown"]} unsummarized')
        status_breakdown = " \u00b7 ".join(status_parts) if status_parts else f"{len(sessions)} sessions"

        # Build session rows
        session_parts = []
        for s in sessions:
            sid = s["session_id"]
            status = s["_status"]
            title = html_escape(s["_title"])
            summary = s["_summary"]
            time_short = format_timestamp_short(s["latest"])
            msgs = s["total_messages"]

            # Detail content
            if summary and not summary.startswith("("):
                detail_body = md_to_html(summary)
            else:
                parts = [f'<p class="raw-ask"><strong>Opening ask:</strong> {html_escape(truncate(s["first_ask"], 300))}</p>']
                if s["last_assistant"]:
                    clean = clean_transcript_text(s["last_assistant"])
                    if clean and len(clean) > 10:
                        parts.append(f'<p class="raw-resp"><strong>Last response:</strong> {html_escape(truncate(clean, 300))}</p>')
                detail_body = "\n".join(parts)

            session_parts.append(f"""<div class="session" data-status="{status}">
  <div class="session-row" onclick="toggleSession(this)" onkeydown="handleKey(event,this,toggleSession)" role="button" tabindex="0" aria-expanded="false">
    <span class="badge {status}">{STATUS_LABELS.get(status, status)}</span>
    <span class="session-title">{title}</span>
    <span class="session-time">{time_short}</span>
    <span class="session-msgs">{msgs} msgs</span>
    <span class="session-chevron"></span>
  </div>
  <div class="session-detail">
    <div class="session-detail-inner">
      <div class="detail-meta">
        <span class="meta-time">{format_timestamp(s["earliest"])} &rarr; {format_timestamp(s["latest"])}</span>
        <span class="meta-sep"></span>
        <span class="meta-msgs">{s["user_msg_count"]} user / {s["assistant_msg_count"]} assistant</span>
        <span class="meta-sep"></span>
        <button class="meta-id" onclick="event.stopPropagation();navigator.clipboard.writeText('{sid}');this.textContent='Copied!';setTimeout(()=>this.textContent='{sid[:8]}…',1200)" title="Click to copy full ID: {sid}">{sid[:8]}&hellip;</button>
      </div>
      <div class="detail-body">{detail_body}</div>
    </div>
  </div>
</div>""")

        n_complete_folder = f_counts.get("complete", 0)
        completed_toggle = ""
        has_non_complete = len(sessions) - n_complete_folder > 0
        if n_complete_folder > 0:
            label = f'{n_complete_folder} completed session{"s" if n_complete_folder != 1 else ""}'
            completed_toggle = f'<button class="show-completed-toggle" onclick="toggleCompleted(this)">{label}</button>'

        folder_parts.append(f"""<section class="folder{' completed-hidden' if n_complete_folder > 0 and has_non_complete else ''}" data-folder="{html_escape(sf)}" data-complete-count="{n_complete_folder}">
  <div class="folder-header" onclick="toggleFolder(this)" onkeydown="handleKey(event,this,toggleFolder)" role="button" tabindex="0" aria-expanded="false">
    <span class="folder-arrow"></span>
    <span class="folder-path">{html_escape(sf)}</span>
    <div class="folder-meta">
      {folder_status_pills}
      <span class="folder-info">{status_breakdown} &middot; {latest_ts}</span>
    </div>
  </div>
  <div class="folder-body">
    {''.join(session_parts)}
    {completed_toggle}
  </div>
</section>""")

    html = f"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Session Report &mdash; Last {days} day(s)</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>
/* ── Reset ─────────────────────────────────────────────── */
*,*::before,*::after {{ box-sizing:border-box; margin:0; padding:0; }}

/* ── Theme: Light ──────────────────────────────────────── */
:root, [data-theme="light"] {{
  --bg: oklch(0.97 0.005 70);
  --surface: oklch(1 0 0);
  --surface-hover: oklch(0.96 0.005 70);
  --border: oklch(0.91 0.008 70);
  --text: oklch(0.18 0.02 50);
  --text-2: oklch(0.45 0.015 50);
  --text-3: oklch(0.65 0.01 50);
  --progress: oklch(0.50 0.18 255);
  --progress-bg: oklch(0.94 0.04 255);
  --blocked: oklch(0.55 0.16 65);
  --blocked-bg: oklch(0.94 0.04 65);
  --handed: oklch(0.50 0.17 300);
  --handed-bg: oklch(0.94 0.04 300);
  --complete: oklch(0.50 0.14 160);
  --complete-bg: oklch(0.94 0.04 160);
  --unknown: oklch(0.70 0.01 50);
  --unknown-bg: transparent;
  --code-bg: oklch(0.95 0.005 70);
  --code-text: oklch(0.45 0.12 40);
  --shadow: 0 1px 3px oklch(0.2 0 0 / 0.06);
  color-scheme: light;
}}

/* ── Theme: Dark ───────────────────────────────────────── */
[data-theme="dark"] {{
  --bg: oklch(0.14 0.01 55);
  --surface: oklch(0.18 0.012 55);
  --surface-hover: oklch(0.22 0.012 55);
  --border: oklch(0.27 0.012 55);
  --text: oklch(0.90 0.01 55);
  --text-2: oklch(0.65 0.01 55);
  --text-3: oklch(0.50 0.01 55);
  --progress: oklch(0.70 0.15 250);
  --progress-bg: oklch(0.25 0.06 250);
  --blocked: oklch(0.75 0.14 70);
  --blocked-bg: oklch(0.25 0.05 70);
  --handed: oklch(0.72 0.14 300);
  --handed-bg: oklch(0.25 0.05 300);
  --complete: oklch(0.68 0.12 160);
  --complete-bg: oklch(0.22 0.04 160);
  --unknown: oklch(0.45 0.01 55);
  --unknown-bg: transparent;
  --code-bg: oklch(0.20 0.01 55);
  --code-text: oklch(0.72 0.1 40);
  --shadow: 0 1px 3px oklch(0 0 0 / 0.2);
  color-scheme: dark;
}}

/* ── Base ──────────────────────────────────────────────── */
body {{
  background: var(--bg); color: var(--text);
  font-family: 'Outfit', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
  line-height: 1.5; padding: 0; margin: 0;
  -webkit-font-smoothing: antialiased;
}}
.wrap {{ max-width: 1100px; margin: 0 auto; padding: 32px 24px; }}
@media (prefers-reduced-motion: reduce) {{
  *, *::before, *::after {{ transition-duration: 0.01ms !important; }}
}}

/* ── Header ────────────────────────────────────────────── */
.header {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 28px; }}
.header h1 {{ font-size: 1.5rem; font-weight: 700; letter-spacing: -0.02em; }}
.header .sub {{ color: var(--text-3); font-size: 0.8rem; margin-top: 2px; }}
.theme-toggle {{
  background: var(--surface); border: 1px solid var(--border); border-radius: 8px;
  width: 36px; height: 36px; cursor: pointer; display: grid; place-items: center;
  font-size: 16px; transition: background 0.15s;
}}
.theme-toggle:hover {{ background: var(--surface-hover); }}
.theme-toggle:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; }}

/* ── Status Strip ──────────────────────────────────────── */
.status-strip {{
  display: flex; align-items: center; gap: 24px; flex-wrap: wrap;
  padding: 14px 0; margin-bottom: 20px;
  border-bottom: 1px solid var(--border);
}}
.status-group {{ display: flex; align-items: center; gap: 6px; font-size: 0.82rem; color: var(--text-2); }}
.status-group .dot {{ width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }}
.status-group strong {{ color: var(--text); font-weight: 600; }}
.status-sep {{ width: 1px; height: 16px; background: var(--border); }}
.status-total {{ font-size: 0.78rem; color: var(--text-3); margin-left: auto; }}

/* ── Controls ──────────────────────────────────────────── */
.controls {{
  display: flex; align-items: center; gap: 6px; flex-wrap: wrap;
  margin-bottom: 36px;
}}
.chip {{
  background: transparent; border: 1px solid var(--border); color: var(--text-2);
  padding: 4px 12px; border-radius: 20px; font-size: 0.75rem; cursor: pointer;
  font-family: inherit; font-weight: 500; transition: all 0.15s;
}}
.chip:hover {{ background: var(--surface-hover); color: var(--text); }}
.chip:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; }}
.chip.active {{ background: var(--text); color: var(--bg); border-color: var(--text); }}
.chip .chip-count {{ opacity: 0.6; font-weight: 400; margin-left: 2px; }}
.chip.active .chip-count {{ opacity: 0.7; }}
.controls-right {{ margin-left: auto; display: flex; gap: 6px; align-items: center; }}
.sort-select {{
  background: var(--surface); border: 1px solid var(--border); color: var(--text-2);
  padding: 5px 10px; border-radius: 8px; font-size: 0.75rem; font-family: inherit;
  cursor: pointer;
}}
.sort-select:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; }}
.search-input {{
  background: var(--surface); border: 1px solid var(--border); color: var(--text);
  padding: 5px 12px; border-radius: 8px; font-size: 0.78rem; font-family: inherit;
  width: 170px; outline: none; transition: border-color 0.15s;
}}
.search-input:focus {{ border-color: var(--text-3); }}
.search-input:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; }}
.bulk-btns {{ display: flex; gap: 4px; }}
.bulk-btn {{
  background: var(--surface); border: 1px solid var(--border); color: var(--text-2);
  padding: 5px 10px; border-radius: 8px; font-size: 0.75rem; cursor: pointer;
  font-family: inherit; transition: all 0.15s;
}}
.bulk-btn:hover {{ background: var(--surface-hover); color: var(--text); }}
.bulk-btn:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; }}

/* ── Empty state ───────────────────────────────────────── */
.empty-state {{
  text-align: center; padding: 48px 24px; color: var(--text-3); font-size: 0.85rem;
  display: none;
}}
.empty-state.visible {{ display: block; }}

/* ── Folder ────────────────────────────────────────────── */
.folder {{
  margin-bottom: 2px;
  border-bottom: 1px solid var(--border);
}}
.folder:last-child {{ border-bottom: none; }}
.folder-header {{
  display: flex; align-items: center; gap: 10px;
  padding: 11px 4px; cursor: pointer; user-select: none;
}}
.folder-header:hover {{ background: var(--surface-hover); border-radius: 6px; }}
.folder-header:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; border-radius: 6px; }}
.folder-arrow {{
  width: 16px; height: 16px; display: grid; place-items: center;
  font-size: 10px; color: var(--text-3); transition: transform 0.15s;
}}
.folder-arrow::before {{ content: "\\25B6"; }}
.folder.open .folder-arrow {{ transform: rotate(90deg); }}
.folder-path {{ font-weight: 600; font-size: 1rem; flex: 1; }}
.folder-meta {{ display: flex; align-items: center; gap: 6px; }}
.fpill {{
  display: inline-flex; align-items: center; justify-content: center;
  min-width: 20px; height: 20px; padding: 0 6px;
  border-radius: 10px; font-size: 0.7rem; font-weight: 600;
}}
.fpill.progress {{ background: var(--progress-bg); color: var(--progress); }}
.fpill.blocked {{ background: var(--blocked-bg); color: var(--blocked); }}
.fpill.handed {{ background: var(--handed-bg); color: var(--handed); }}
.folder-info {{ font-size: 0.75rem; color: var(--text-3); }}
.folder-body {{ display: none; padding: 0 0 6px 0; }}
.folder.open .folder-body {{ display: block; }}

/* ── Session Row ───────────────────────────────────────── */
.session {{ border-radius: 6px; margin: 1px 0; }}
.session.filter-hidden, .session.search-hidden {{ display: none; }}
.session-row {{
  display: flex; align-items: center; gap: 10px;
  padding: 7px 8px 7px 28px; cursor: pointer; border-radius: 6px;
  transition: background 0.1s;
}}
.session-row:hover {{ background: var(--surface-hover); }}
.session-row:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; }}
.badge {{
  display: inline-flex; align-items: center;
  padding: 2px 10px; border-radius: 4px;
  font-size: 0.7rem; font-weight: 600; text-transform: uppercase;
  letter-spacing: 0.03em; white-space: nowrap; flex-shrink: 0;
  min-width: 78px; justify-content: center;
}}
.badge.in_progress {{ background: var(--progress-bg); color: var(--progress); }}
.badge.blocked {{ background: var(--blocked-bg); color: var(--blocked); }}
.badge.handed_off {{ background: var(--handed-bg); color: var(--handed); }}
.badge.complete {{ background: var(--complete-bg); color: var(--complete); }}
.badge.unknown {{
  background: transparent; color: var(--unknown);
  border: 1px dashed var(--border); font-weight: 400;
  text-transform: none; letter-spacing: 0; font-size: 0.7rem;
  min-width: 78px;
}}
.session-title {{
  flex: 1; font-size: 0.84rem; font-weight: 400;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
  color: var(--text);
}}
.session[data-status="complete"] .session-title,
.session[data-status="handed_off"] .session-title {{ color: var(--text-2); }}
.session[data-status="unknown"] .session-title {{ color: var(--text-2); }}
.session-time {{ font-size: 0.75rem; color: var(--text-3); white-space: nowrap; flex-shrink: 0; }}
.session-msgs {{ font-size: 0.75rem; color: var(--text-3); white-space: nowrap; flex-shrink: 0; min-width: 52px; text-align: right; }}
.session-chevron {{
  width: 14px; height: 14px; flex-shrink: 0; display: grid; place-items: center;
  font-size: 8px; color: var(--text-3); transition: transform 0.2s cubic-bezier(0.16,1,0.3,1);
}}
.session-chevron::before {{ content: "\\25B6"; }}
.session.expanded .session-chevron {{ transform: rotate(90deg); }}

/* ── Session Detail ────────────────────────────────────── */
.session-detail {{
  display: grid; grid-template-rows: 0fr;
  transition: grid-template-rows 0.25s cubic-bezier(0.16,1,0.3,1);
}}
.session.expanded .session-detail {{ grid-template-rows: 1fr; }}
.session-detail-inner {{ overflow: hidden; }}
.session-detail-inner > div {{ padding: 6px 28px 14px; }}
.detail-meta {{
  display: flex; align-items: center; gap: 0; flex-wrap: wrap;
  font-size: 0.75rem; color: var(--text-3); margin-bottom: 10px;
  padding-top: 6px; border-top: 1px solid var(--border);
}}
.meta-sep {{ width: 1px; height: 12px; background: var(--border); margin: 0 10px; flex-shrink: 0; }}
.meta-id {{
  background: none; border: none; color: var(--text-3); font-family: 'SFMono-Regular','Cascadia Code',Consolas,monospace;
  font-size: 0.7rem; cursor: pointer; padding: 1px 4px; border-radius: 3px; transition: all 0.15s;
}}
.meta-id:hover {{ background: var(--surface-hover); color: var(--text-2); }}
.detail-body {{ font-size: 0.82rem; line-height: 1.65; color: var(--text-2); }}
.detail-body h2 {{ font-size: 0.85rem; font-weight: 600; color: var(--text); margin: 14px 0 4px; }}
.detail-body h3 {{ font-size: 0.88rem; font-weight: 600; color: var(--text); margin: 12px 0 4px; }}
.detail-body ul {{ margin: 4px 0 8px 18px; }}
.detail-body li {{ margin-bottom: 3px; }}
.detail-body p {{ margin: 4px 0; }}
.detail-body code {{ background: var(--code-bg); padding: 1px 5px; border-radius: 3px; font-size: 0.76rem; color: var(--code-text); font-family: 'SFMono-Regular','Cascadia Code',Consolas,monospace; }}
.detail-body strong {{ color: var(--text); font-weight: 600; }}
.raw-ask, .raw-resp {{ color: var(--text-2); }}
.session[data-status="unknown"] .detail-body {{
  border-left: 3px solid var(--border); padding-left: 14px; margin-left: 2px;
}}

/* ── Completed session collapsing ─────────────────────── */
.folder.completed-hidden .session[data-status="complete"] {{ display: none; }}
.show-completed-toggle {{
  width: 100%; padding: 6px 28px;
  background: none; border: none; border-top: 1px dashed var(--border);
  color: var(--text-3); font-size: 0.75rem; font-family: inherit;
  cursor: pointer; text-align: left; margin-top: 2px; transition: color 0.15s;
}}
.show-completed-toggle:hover {{ color: var(--text-2); }}
.show-completed-toggle:focus-visible {{ outline: 2px solid var(--progress); outline-offset: 2px; }}
.folder.completed-hidden .show-completed-toggle::before {{ content: "\\25B6  "; font-size: 0.6rem; }}
.folder:not(.completed-hidden) .show-completed-toggle::before {{ content: "\\25BC  "; font-size: 0.6rem; }}

/* ── Footer ────────────────────────────────────────────── */
.footer {{ color: var(--text-3); font-size: 0.7rem; margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--border); }}

/* ── Responsive ───────────────────────────────────────── */
@media (max-width: 768px) {{
  .wrap {{ padding: 16px 12px; }}
  .header {{ flex-wrap: wrap; gap: 8px; }}
  .status-strip {{ gap: 12px; }}
  .controls {{ flex-direction: column; align-items: stretch; gap: 8px; }}
  .controls-right {{ margin-left: 0; flex-wrap: wrap; }}
  .search-input {{ width: 100%; }}
  .session-row {{ padding-left: 12px; gap: 6px; }}
  .session-time, .session-msgs {{ display: none; }}
  .folder-info {{ display: none; }}
}}
</style>
</head>
<body>
<div class="wrap">

<div class="header">
  <div>
    <h1>Session Report</h1>
    <div class="sub">Last {days} day(s) &middot; {now_str}</div>
  </div>
  <button class="theme-toggle" onclick="toggleTheme()" title="Toggle theme" aria-label="Toggle theme">
    <span class="theme-icon"></span>
  </button>
</div>

<div class="status-strip">
  <div class="status-group"><span class="dot" style="background:var(--progress)"></span> <strong>{n_progress}</strong> in progress</div>
  <div class="status-group"><span class="dot" style="background:var(--blocked)"></span> <strong>{n_blocked}</strong> blocked</div>
  <div class="status-group"><span class="dot" style="background:var(--handed)"></span> <strong>{n_handed}</strong> handed off</div>
  <div class="status-group"><span class="dot" style="background:var(--complete)"></span> <strong>{n_complete}</strong> complete</div>
  {"<div class='status-group'><span class='dot' style='background:var(--unknown)'></span> <strong>" + str(n_unknown) + "</strong> unsummarized</div>" if n_unknown else ""}
  <span class="status-sep"></span>
  <span class="status-total">{len(all_sessions)} sessions &middot; {len(by_project)} folders &middot; {total_msgs:,} messages</span>
</div>

<div class="controls">
  <button class="chip active" data-status="all" onclick="filterStatus('all',this)">All <span class="chip-count">{len(all_sessions)}</span></button>
  <button class="chip" data-status="in_progress" onclick="filterStatus('in_progress',this)">In Progress <span class="chip-count">{n_progress}</span></button>
  {"<button class='chip' data-status='blocked' onclick=\"filterStatus('blocked',this)\">Blocked <span class='chip-count'>" + str(n_blocked) + "</span></button>" if n_blocked else ""}
  <button class="chip" data-status="handed_off" onclick="filterStatus('handed_off',this)">Handed Off <span class="chip-count">{n_handed}</span></button>
  <button class="chip" data-status="complete" onclick="filterStatus('complete',this)">Complete <span class="chip-count">{n_complete}</span></button>
  {"<button class='chip' data-status='unknown' onclick=\"filterStatus('unknown',this)\">Unsummarized <span class='chip-count'>" + str(n_unknown) + "</span></button>" if n_unknown else ""}
  <div class="controls-right">
    <select class="sort-select" onchange="sortSessions(this.value)">
      <option value="recent">Most Recent</option>
      <option value="status">By Status</option>
      <option value="messages">Most Messages</option>
    </select>
    <input type="text" class="search-input" placeholder="Search..." oninput="searchSessions(this.value)">
    <div class="bulk-btns">
      <button class="bulk-btn" onclick="expandAllFolders()">Expand</button>
      <button class="bulk-btn" onclick="collapseAllFolders()">Collapse</button>
    </div>
  </div>
</div>

<main id="main">
{''.join(folder_parts)}
<div class="empty-state" id="emptyState">No sessions match this filter.</div>
</main>

<div class="footer">
  Summaries by Claude Code &middot; Cache: {str(CACHE_FILE)}
</div>

</div>
<script>
/* Theme */
(function() {{
  const saved = localStorage.getItem('sr-theme');
  const pref = saved || (matchMedia('(prefers-color-scheme:light)').matches ? 'light' : 'dark');
  document.documentElement.setAttribute('data-theme', pref);
  updateThemeIcon();
}})();

function toggleTheme() {{
  const el = document.documentElement;
  const next = el.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
  el.setAttribute('data-theme', next);
  localStorage.setItem('sr-theme', next);
  updateThemeIcon();
}}

function updateThemeIcon() {{
  const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
  document.querySelectorAll('.theme-icon').forEach(el => el.textContent = isDark ? '\\u2600' : '\\u263E');
}}

/* Folders — open all, but collapse folders with only complete/unknown sessions */
document.querySelectorAll('.folder').forEach(f => {{
  const sessions = f.querySelectorAll('.session');
  const hasActive = [...sessions].some(s => ['in_progress','blocked'].includes(s.dataset.status));
  if (hasActive || sessions.length === 0) {{
    f.classList.add('open');
  }} else {{
    const hasHandedOff = [...sessions].some(s => s.dataset.status === 'handed_off');
    if (hasHandedOff) f.classList.add('open');
  }}
  const header = f.querySelector('.folder-header');
  if (header) header.setAttribute('aria-expanded', f.classList.contains('open'));
}});

function handleKey(e, el, fn) {{
  if (e.key === 'Enter' || e.key === ' ') {{ e.preventDefault(); fn(el); }}
}}
function toggleFolder(header) {{
  const folder = header.closest('.folder');
  folder.classList.toggle('open');
  header.setAttribute('aria-expanded', folder.classList.contains('open'));
}}
function expandAllFolders() {{
  document.querySelectorAll('.folder').forEach(f => f.classList.add('open'));
}}
function collapseAllFolders() {{
  document.querySelectorAll('.folder').forEach(f => f.classList.remove('open'));
}}

/* Sessions */
function toggleSession(row) {{
  const session = row.closest('.session');
  session.classList.toggle('expanded');
  row.setAttribute('aria-expanded', session.classList.contains('expanded'));
}}

/* Completed session toggle */
function toggleCompleted(btn) {{
  const folder = btn.closest('.folder');
  folder.classList.toggle('completed-hidden');
  const n = folder.dataset.completeCount || 0;
  const label = n + ' completed session' + (n == 1 ? '' : 's');
  btn.textContent = label;
}}

/* Empty state */
function updateEmptyState() {{
  const visibleSessions = document.querySelectorAll('.session:not(.filter-hidden):not(.search-hidden)');
  const el = document.getElementById('emptyState');
  if (el) el.classList.toggle('visible', visibleSessions.length === 0);
}}

/* Filter by status */
let activeFilter = 'all';
function filterStatus(status, btn) {{
  activeFilter = status;
  document.querySelectorAll('.chip[data-status]').forEach(c => c.classList.remove('active'));
  btn.classList.add('active');
  document.querySelectorAll('.session').forEach(s => {{
    if (status === 'all' || s.dataset.status === status) {{
      s.classList.remove('filter-hidden');
    }} else {{
      s.classList.add('filter-hidden');
    }}
  }});
  /* When filtering to complete, temporarily unhide completed sessions */
  document.querySelectorAll('.folder').forEach(f => {{
    if (status === 'complete') {{
      f.classList.remove('completed-hidden');
    }} else if (status === 'all' && f.dataset.completeCount > 0) {{
      const hasNonComplete = f.querySelectorAll('.session:not([data-status="complete"])').length > 0;
      if (hasNonComplete) f.classList.add('completed-hidden');
    }}
    const visible = f.querySelectorAll('.session:not(.filter-hidden):not(.search-hidden)');
    f.style.display = visible.length ? '' : 'none';
    if (visible.length) f.classList.add('open');
  }});
  updateEmptyState();
}}

/* Search */
function searchSessions(q) {{
  q = q.toLowerCase().trim();
  document.querySelectorAll('.folder').forEach(folder => {{
    const fname = folder.dataset.folder.toLowerCase();
    let anyVisible = false;
    folder.querySelectorAll('.session').forEach(s => {{
      if (!q) {{
        s.classList.remove('search-hidden');
        anyVisible = true;
        return;
      }}
      const text = s.textContent.toLowerCase();
      if (text.includes(q) || fname.includes(q)) {{
        s.classList.remove('search-hidden');
        anyVisible = true;
      }} else {{
        s.classList.add('search-hidden');
      }}
    }});
    folder.style.display = anyVisible || !q ? '' : 'none';
    if (q && anyVisible) folder.classList.add('open');
  }});
  updateEmptyState();
}}

/* Sort */
const STATUS_ORD = {{blocked:0, in_progress:1, handed_off:2, unknown:3, complete:4}};
function sortSessions(by) {{
  document.querySelectorAll('.folder-body').forEach(body => {{
    const sessions = [...body.querySelectorAll('.session')];
    sessions.sort((a,b) => {{
      if (by === 'status') return (STATUS_ORD[a.dataset.status]||3) - (STATUS_ORD[b.dataset.status]||3);
      if (by === 'messages') {{
        const am = parseInt(a.querySelector('.session-msgs').textContent) || 0;
        const bm = parseInt(b.querySelector('.session-msgs').textContent) || 0;
        return bm - am;
      }}
      return 0; // recent is default order from Python
    }});
    sessions.forEach(s => body.appendChild(s));
  }});
}}
</script>
</body>
</html>"""
    return html


# ─── Text output (terminal) ──────────────────────────────────────────────────


def print_text_report(all_sessions, summaries, days):
    by_project = defaultdict(list)
    for s in all_sessions:
        by_project[s["cwd"] or s["project_path"]].append(s)

    print(f"Found {len(all_sessions)} active session(s) across {len(by_project)} folder(s)\n")

    for folder, sessions in sorted(
        by_project.items(), key=lambda x: max(s["latest"] for s in x[1]), reverse=True
    ):
        sf = short_path(folder)
        print(f"{'─'*80}")
        print(f"  FOLDER: {sf}")
        print(f"  Sessions: {len(sessions)}")
        print(f"{'─'*80}")

        for i, s in enumerate(sessions, 1):
            sid = s["session_id"]
            s_data = summaries.get(sid, {})
            status = s_data.get("status", "unknown") if isinstance(s_data, dict) else "unknown"
            status_label = STATUS_LABELS.get(status, status).upper()

            print(f"\n  [{status_label}] Session {i}/{len(sessions)}  [{sid[:8]}...]")
            print(f"  Started:  {format_timestamp(s['earliest'])}")
            print(f"  Latest:   {format_timestamp(s['latest'])}")
            print(f"  Messages: {s['total_messages']} total ({s['user_msg_count']} user, {s['assistant_msg_count']} assistant)")

            summary = s_data.get("summary", "") if isinstance(s_data, dict) else (s_data if isinstance(s_data, str) else "")
            if summary and not summary.startswith("("):
                print(f"\n{summary}")
            else:
                print(f"\n  OPENING ASK:")
                print(f"    {truncate(s['first_ask'], 200)}")
                if len(s["topics"]) > 1:
                    print(f"\n  TOPICS ({len(s['topics'])} user prompts):")
                    show = s["topics"]
                    if len(show) > 8:
                        for t in show[:5]:
                            print(f"    - {t}")
                        print(f"    ... ({len(show) - 7} more) ...")
                        for t in show[-2:]:
                            print(f"    - {t}")
                    else:
                        for t in show:
                            print(f"    - {t}")
                print(f"\n  WHAT'S NEXT:")
                if s["last_user"]:
                    clean = clean_user_text(s["last_user"])
                    if clean:
                        print(f"    Last ask: {truncate(clean, 200)}")
                if s["last_assistant"]:
                    text = clean_transcript_text(s["last_assistant"])
                    if text and len(text) > 10:
                        print(f"    Last response: {truncate(text, 200)}")
            print()

    total_msgs = sum(s["total_messages"] for s in all_sessions)
    total_user = sum(s["user_msg_count"] for s in all_sessions)
    print(f"\n{'='*80}")
    print(f"  SUMMARY")
    print(f"{'='*80}")
    print(f"  Total sessions:  {len(all_sessions)}")
    print(f"  Total messages:  {total_msgs} ({total_user} user prompts)")
    print(f"  Active folders:  {len(by_project)}")
    print(f"\n  Most active folders:")
    folder_activity = sorted(by_project.items(), key=lambda x: sum(s["total_messages"] for s in x[1]), reverse=True)
    for folder, sessions in folder_activity[:10]:
        msg_count = sum(s["total_messages"] for s in sessions)
        sf = short_path(folder)
        print(f"    {sf:<50} {len(sessions):>2} session(s), {msg_count:>5} msgs")
    print()


# ─── Main ─────────────────────────────────────────────────────────────────────


def cleanup_old_reports(keep=10):
    if not REPORT_DIR.exists():
        return
    reports = sorted(REPORT_DIR.glob("session-report-*.html"), key=lambda f: f.stat().st_mtime, reverse=True)
    for old in reports[keep:]:
        try:
            old.unlink()
        except OSError:
            pass
    removed = len(reports) - min(len(reports), keep)
    if removed > 0:
        print(f"  Cleaned up {removed} old report(s)")


def normalize_args(argv):
    normalized = []
    bare_words = {
        "text": "--text", "refresh": "--refresh", "no-ai": "--no-ai",
        "no-open": "--no-open", "collect": "--collect",
        "review-statuses": "--review-statuses",
    }
    for arg in argv:
        normalized.append(bare_words.get(arg.lower(), arg))
    return normalized


def main():
    parser = argparse.ArgumentParser(description="Claude Code Session Reporter")
    parser.add_argument("days", nargs="?", type=int, default=3, help="Days to look back (default: 3)")
    parser.add_argument("--no-ai", action="store_true", help="Ignore cached summaries, show raw output")
    parser.add_argument("--refresh", action="store_true", help="With --collect: include all sessions regardless of cache")
    parser.add_argument("--text", action="store_true", help="Terminal text output instead of HTML")
    parser.add_argument("--no-open", action="store_true", help="Generate HTML but don't open browser")
    parser.add_argument("--limit", type=int, default=0, help="Max sessions to scan (0 = unlimited)")
    parser.add_argument("--collect", action="store_true", help="Output JSON of sessions needing summaries")
    parser.add_argument("--collect-file", type=str, default=None, help="Path for collect output")
    parser.add_argument("--max-collect", type=int, default=15, help="Max sessions to collect for summarization (default: 15)")
    parser.add_argument("--update-cache", type=str, default=None, metavar="FILE", help="Merge summaries from a JSON file into the cache")
    parser.add_argument("--review-statuses", action="store_true", help="Output folder-grouped summaries for cross-session status review")
    parser.add_argument("--update-statuses", type=str, default=None, metavar="FILE", help="Apply status corrections from a JSON file")
    args = parser.parse_args(normalize_args(sys.argv[1:]))

    if args.update_cache:
        print("Updating summary cache...")
        update_cache_from_file(args.update_cache)
        return

    if args.update_statuses:
        print("Applying status corrections...")
        update_statuses_from_file(args.update_statuses)
        return

    days = args.days

    print(f"\n{'='*80}")
    print(f"  CLAUDE CODE SESSION REPORT - Last {days} day(s)")
    print(f"  Generated: {datetime.now().strftime('%Y-%m-%d %I:%M %p')}")
    print(f"{'='*80}\n")

    all_sessions = collect_sessions(days)
    if not all_sessions:
        print(f"No sessions with activity in the last {days} day(s).\n")
        if args.collect:
            output_path = args.collect_file or str(REPORT_DIR / "_collect.json")
            REPORT_DIR.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump({"sessions": [], "total_found": 0, "already_cached": 0, "too_short": 0, "needs_summary": 0}, f)
            print(f"  Collect output: {output_path}")
        return

    if args.limit > 0 and len(all_sessions) > args.limit:
        print(f"  Limiting to {args.limit} most recent sessions (of {len(all_sessions)} found)")
        all_sessions = all_sessions[: args.limit]

    if args.collect:
        data = collect_for_summarization(all_sessions, args.max_collect, args.refresh)
        output_path = args.collect_file or str(REPORT_DIR / "_collect.json")
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"  Total sessions found: {data['total_found']}")
        print(f"  Already cached: {data['already_cached']}")
        print(f"  Too short for summary: {data['too_short']}")
        print(f"  Needs summarization: {data['needs_summary']}")
        if data['needs_summary'] < data['total_found'] - data['already_cached'] - data['too_short']:
            print(f"  (capped at --max-collect {args.max_collect}; run again for more)")
        print(f"  Collect output: {output_path}")
        return

    if args.review_statuses:
        summaries = load_cached_summaries(all_sessions, False)
        data = prepare_review_data(all_sessions, summaries)
        output_path = str(REPORT_DIR / "_review.json")
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"  Folders needing cross-session review: {data['needs_review']}")
        print(f"  Review output: {output_path}")
        return

    summaries = load_cached_summaries(all_sessions, args.no_ai)

    if args.text:
        print_text_report(all_sessions, summaries, days)
    else:
        html = generate_html(all_sessions, summaries, days)
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        report_file = REPORT_DIR / f"session-report-{datetime.now().strftime('%Y%m%d-%H%M%S')}.html"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(html)
        cleanup_old_reports(keep=10)
        print(f"Report saved: {report_file}")
        if not args.no_open:
            webbrowser.open(str(report_file))
            print("Opened in browser.")


if __name__ == "__main__":
    main()
